// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/queue_service/queue_service.proto

package queue_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                 // Must match a topic defined in revenueiq_dev_kit, e.g. "EMAIL"
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                   // Flexible type for within the service, e.g. "signup"
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"` // The key under which relevant data is stored in Redis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_proto_queue_service_queue_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_service_queue_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_queue_service_queue_service_proto_rawDescGZIP(), []int{0}
}

func (x *PublishEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublishEventRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_proto_queue_service_queue_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_service_queue_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_queue_service_queue_service_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_queue_service_queue_service_proto protoreflect.FileDescriptor

const file_proto_queue_service_queue_service_proto_rawDesc = "" +
	"\n" +
	"'proto/queue_service/queue_service.proto\x12\rqueue_service\"X\n" +
	"\x13PublishEventRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\"J\n" +
	"\x14PublishEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2g\n" +
	"\fQueueService\x12W\n" +
	"\fPublishEvent\x12\".queue_service.PublishEventRequest\x1a#.queue_service.PublishEventResponseBHZFgithub.com/RevenueIQ/revenueiq_dev_kit/proto/queue_service;queue_protob\x06proto3"

var (
	file_proto_queue_service_queue_service_proto_rawDescOnce sync.Once
	file_proto_queue_service_queue_service_proto_rawDescData []byte
)

func file_proto_queue_service_queue_service_proto_rawDescGZIP() []byte {
	file_proto_queue_service_queue_service_proto_rawDescOnce.Do(func() {
		file_proto_queue_service_queue_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_service_queue_service_proto_rawDesc), len(file_proto_queue_service_queue_service_proto_rawDesc)))
	})
	return file_proto_queue_service_queue_service_proto_rawDescData
}

var file_proto_queue_service_queue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_queue_service_queue_service_proto_goTypes = []any{
	(*PublishEventRequest)(nil),  // 0: queue_service.PublishEventRequest
	(*PublishEventResponse)(nil), // 1: queue_service.PublishEventResponse
}
var file_proto_queue_service_queue_service_proto_depIdxs = []int32{
	0, // 0: queue_service.QueueService.PublishEvent:input_type -> queue_service.PublishEventRequest
	1, // 1: queue_service.QueueService.PublishEvent:output_type -> queue_service.PublishEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_queue_service_queue_service_proto_init() }
func file_proto_queue_service_queue_service_proto_init() {
	if File_proto_queue_service_queue_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_service_queue_service_proto_rawDesc), len(file_proto_queue_service_queue_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_queue_service_queue_service_proto_goTypes,
		DependencyIndexes: file_proto_queue_service_queue_service_proto_depIdxs,
		MessageInfos:      file_proto_queue_service_queue_service_proto_msgTypes,
	}.Build()
	File_proto_queue_service_queue_service_proto = out.File
	file_proto_queue_service_queue_service_proto_goTypes = nil
	file_proto_queue_service_queue_service_proto_depIdxs = nil
}
