// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/analytics_service/analytics_service.proto

package analytics_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FleetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeWindow    string                 `protobuf:"bytes,1,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"` // e.g. 1h, 24h, 7d
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetMetricsRequest) Reset() {
	*x = FleetMetricsRequest{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetricsRequest) ProtoMessage() {}

func (x *FleetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetricsRequest.ProtoReflect.Descriptor instead.
func (*FleetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{0}
}

func (x *FleetMetricsRequest) GetTimeWindow() string {
	if x != nil {
		return x.TimeWindow
	}
	return ""
}

type FleetMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalDrones          int32                  `protobuf:"varint,1,opt,name=total_drones,json=totalDrones,proto3" json:"total_drones,omitempty"`
	ActiveDrones         int32                  `protobuf:"varint,2,opt,name=active_drones,json=activeDrones,proto3" json:"active_drones,omitempty"`
	MaintenanceDrones    int32                  `protobuf:"varint,3,opt,name=maintenance_drones,json=maintenanceDrones,proto3" json:"maintenance_drones,omitempty"`
	AvgBatteryDrainRate  float64                `protobuf:"fixed64,4,opt,name=avg_battery_drain_rate,json=avgBatteryDrainRate,proto3" json:"avg_battery_drain_rate,omitempty"`
	MaintenanceCount_24H int32                  `protobuf:"varint,5,opt,name=maintenance_count_24h,json=maintenanceCount24h,proto3" json:"maintenance_count_24h,omitempty"`
	Timestamp            int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FleetMetricsResponse) Reset() {
	*x = FleetMetricsResponse{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetricsResponse) ProtoMessage() {}

func (x *FleetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetricsResponse.ProtoReflect.Descriptor instead.
func (*FleetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{1}
}

func (x *FleetMetricsResponse) GetTotalDrones() int32 {
	if x != nil {
		return x.TotalDrones
	}
	return 0
}

func (x *FleetMetricsResponse) GetActiveDrones() int32 {
	if x != nil {
		return x.ActiveDrones
	}
	return 0
}

func (x *FleetMetricsResponse) GetMaintenanceDrones() int32 {
	if x != nil {
		return x.MaintenanceDrones
	}
	return 0
}

func (x *FleetMetricsResponse) GetAvgBatteryDrainRate() float64 {
	if x != nil {
		return x.AvgBatteryDrainRate
	}
	return 0
}

func (x *FleetMetricsResponse) GetMaintenanceCount_24H() int32 {
	if x != nil {
		return x.MaintenanceCount_24H
	}
	return 0
}

func (x *FleetMetricsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type OrderMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeWindow    string                 `protobuf:"bytes,1,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderMetricsRequest) Reset() {
	*x = OrderMetricsRequest{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMetricsRequest) ProtoMessage() {}

func (x *OrderMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMetricsRequest.ProtoReflect.Descriptor instead.
func (*OrderMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{2}
}

func (x *OrderMetricsRequest) GetTimeWindow() string {
	if x != nil {
		return x.TimeWindow
	}
	return ""
}

type OrderMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders          int64                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	CompletedOrders      int64                  `protobuf:"varint,2,opt,name=completed_orders,json=completedOrders,proto3" json:"completed_orders,omitempty"`
	FailedOrders         int64                  `protobuf:"varint,3,opt,name=failed_orders,json=failedOrders,proto3" json:"failed_orders,omitempty"`
	DeliverySuccessRate  float64                `protobuf:"fixed64,4,opt,name=delivery_success_rate,json=deliverySuccessRate,proto3" json:"delivery_success_rate,omitempty"` // percentage
	AvgFlightTimeMinutes float64                `protobuf:"fixed64,5,opt,name=avg_flight_time_minutes,json=avgFlightTimeMinutes,proto3" json:"avg_flight_time_minutes,omitempty"`
	TotalRevenue         float64                `protobuf:"fixed64,6,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	Timestamp            int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrderMetricsResponse) Reset() {
	*x = OrderMetricsResponse{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMetricsResponse) ProtoMessage() {}

func (x *OrderMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMetricsResponse.ProtoReflect.Descriptor instead.
func (*OrderMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{3}
}

func (x *OrderMetricsResponse) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *OrderMetricsResponse) GetCompletedOrders() int64 {
	if x != nil {
		return x.CompletedOrders
	}
	return 0
}

func (x *OrderMetricsResponse) GetFailedOrders() int64 {
	if x != nil {
		return x.FailedOrders
	}
	return 0
}

func (x *OrderMetricsResponse) GetDeliverySuccessRate() float64 {
	if x != nil {
		return x.DeliverySuccessRate
	}
	return 0
}

func (x *OrderMetricsResponse) GetAvgFlightTimeMinutes() float64 {
	if x != nil {
		return x.AvgFlightTimeMinutes
	}
	return 0
}

func (x *OrderMetricsResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderMetricsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UtilizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       string                 `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtilizationRequest) Reset() {
	*x = UtilizationRequest{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilizationRequest) ProtoMessage() {}

func (x *UtilizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilizationRequest.ProtoReflect.Descriptor instead.
func (*UtilizationRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{4}
}

func (x *UtilizationRequest) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

type DroneStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DroneId          string                 `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	TotalDeliveries  int32                  `protobuf:"varint,2,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	TotalDistanceKm  float64                `protobuf:"fixed64,3,opt,name=total_distance_km,json=totalDistanceKm,proto3" json:"total_distance_km,omitempty"`
	TotalFlightHours float64                `protobuf:"fixed64,4,opt,name=total_flight_hours,json=totalFlightHours,proto3" json:"total_flight_hours,omitempty"`
	IdleHours        float64                `protobuf:"fixed64,5,opt,name=idle_hours,json=idleHours,proto3" json:"idle_hours,omitempty"`
	AvgSignalQuality float64                `protobuf:"fixed64,6,opt,name=avg_signal_quality,json=avgSignalQuality,proto3" json:"avg_signal_quality,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DroneStats) Reset() {
	*x = DroneStats{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneStats) ProtoMessage() {}

func (x *DroneStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneStats.ProtoReflect.Descriptor instead.
func (*DroneStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{5}
}

func (x *DroneStats) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *DroneStats) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *DroneStats) GetTotalDistanceKm() float64 {
	if x != nil {
		return x.TotalDistanceKm
	}
	return 0
}

func (x *DroneStats) GetTotalFlightHours() float64 {
	if x != nil {
		return x.TotalFlightHours
	}
	return 0
}

func (x *DroneStats) GetIdleHours() float64 {
	if x != nil {
		return x.IdleHours
	}
	return 0
}

func (x *DroneStats) GetAvgSignalQuality() float64 {
	if x != nil {
		return x.AvgSignalQuality
	}
	return 0
}

type UtilizationResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Drones                     []*DroneStats          `protobuf:"bytes,1,rep,name=drones,proto3" json:"drones,omitempty"`
	AvgFleetUtilizationPercent float64                `protobuf:"fixed64,2,opt,name=avg_fleet_utilization_percent,json=avgFleetUtilizationPercent,proto3" json:"avg_fleet_utilization_percent,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UtilizationResponse) Reset() {
	*x = UtilizationResponse{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilizationResponse) ProtoMessage() {}

func (x *UtilizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilizationResponse.ProtoReflect.Descriptor instead.
func (*UtilizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{6}
}

func (x *UtilizationResponse) GetDrones() []*DroneStats {
	if x != nil {
		return x.Drones
	}
	return nil
}

func (x *UtilizationResponse) GetAvgFleetUtilizationPercent() float64 {
	if x != nil {
		return x.AvgFleetUtilizationPercent
	}
	return 0
}

type FailureEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // e.g. CONGESTION, TELEMETRY_ALERT, DELIVERY_DROP, PAYMENT_FAIL
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureEvent) Reset() {
	*x = FailureEvent{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureEvent) ProtoMessage() {}

func (x *FailureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureEvent.ProtoReflect.Descriptor instead.
func (*FailureEvent) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{7}
}

func (x *FailureEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FailureEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FailureEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FailureEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FailureEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureRequest) Reset() {
	*x = FailureRequest{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureRequest) ProtoMessage() {}

func (x *FailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureRequest.ProtoReflect.Descriptor instead.
func (*FailureRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{8}
}

func (x *FailureRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FailureRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FailureReportResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Failures                []*FailureEvent        `protobuf:"bytes,1,rep,name=failures,proto3" json:"failures,omitempty"`
	TotalFailures           int32                  `protobuf:"varint,2,opt,name=total_failures,json=totalFailures,proto3" json:"total_failures,omitempty"`
	ChargingCongestionCount int32                  `protobuf:"varint,3,opt,name=charging_congestion_count,json=chargingCongestionCount,proto3" json:"charging_congestion_count,omitempty"`
	LowBatteryAlertsCount   int32                  `protobuf:"varint,4,opt,name=low_battery_alerts_count,json=lowBatteryAlertsCount,proto3" json:"low_battery_alerts_count,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FailureReportResponse) Reset() {
	*x = FailureReportResponse{}
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureReportResponse) ProtoMessage() {}

func (x *FailureReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_service_analytics_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureReportResponse.ProtoReflect.Descriptor instead.
func (*FailureReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_service_analytics_service_proto_rawDescGZIP(), []int{9}
}

func (x *FailureReportResponse) GetFailures() []*FailureEvent {
	if x != nil {
		return x.Failures
	}
	return nil
}

func (x *FailureReportResponse) GetTotalFailures() int32 {
	if x != nil {
		return x.TotalFailures
	}
	return 0
}

func (x *FailureReportResponse) GetChargingCongestionCount() int32 {
	if x != nil {
		return x.ChargingCongestionCount
	}
	return 0
}

func (x *FailureReportResponse) GetLowBatteryAlertsCount() int32 {
	if x != nil {
		return x.LowBatteryAlertsCount
	}
	return 0
}

var File_proto_analytics_service_analytics_service_proto protoreflect.FileDescriptor

const file_proto_analytics_service_analytics_service_proto_rawDesc = "" +
	"\n" +
	"/proto/analytics_service/analytics_service.proto\x12\x11analytics_service\"6\n" +
	"\x13FleetMetricsRequest\x12\x1f\n" +
	"\vtime_window\x18\x01 \x01(\tR\n" +
	"timeWindow\"\x94\x02\n" +
	"\x14FleetMetricsResponse\x12!\n" +
	"\ftotal_drones\x18\x01 \x01(\x05R\vtotalDrones\x12#\n" +
	"\ractive_drones\x18\x02 \x01(\x05R\factiveDrones\x12-\n" +
	"\x12maintenance_drones\x18\x03 \x01(\x05R\x11maintenanceDrones\x123\n" +
	"\x16avg_battery_drain_rate\x18\x04 \x01(\x01R\x13avgBatteryDrainRate\x122\n" +
	"\x15maintenance_count_24h\x18\x05 \x01(\x05R\x13maintenanceCount24h\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"6\n" +
	"\x13OrderMetricsRequest\x12\x1f\n" +
	"\vtime_window\x18\x01 \x01(\tR\n" +
	"timeWindow\"\xb7\x02\n" +
	"\x14OrderMetricsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x03R\vtotalOrders\x12)\n" +
	"\x10completed_orders\x18\x02 \x01(\x03R\x0fcompletedOrders\x12#\n" +
	"\rfailed_orders\x18\x03 \x01(\x03R\ffailedOrders\x122\n" +
	"\x15delivery_success_rate\x18\x04 \x01(\x01R\x13deliverySuccessRate\x125\n" +
	"\x17avg_flight_time_minutes\x18\x05 \x01(\x01R\x14avgFlightTimeMinutes\x12#\n" +
	"\rtotal_revenue\x18\x06 \x01(\x01R\ftotalRevenue\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"/\n" +
	"\x12UtilizationRequest\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\"\xf9\x01\n" +
	"\n" +
	"DroneStats\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\x12)\n" +
	"\x10total_deliveries\x18\x02 \x01(\x05R\x0ftotalDeliveries\x12*\n" +
	"\x11total_distance_km\x18\x03 \x01(\x01R\x0ftotalDistanceKm\x12,\n" +
	"\x12total_flight_hours\x18\x04 \x01(\x01R\x10totalFlightHours\x12\x1d\n" +
	"\n" +
	"idle_hours\x18\x05 \x01(\x01R\tidleHours\x12,\n" +
	"\x12avg_signal_quality\x18\x06 \x01(\x01R\x10avgSignalQuality\"\x8f\x01\n" +
	"\x13UtilizationResponse\x125\n" +
	"\x06drones\x18\x01 \x03(\v2\x1d.analytics_service.DroneStatsR\x06drones\x12A\n" +
	"\x1davg_fleet_utilization_percent\x18\x02 \x01(\x01R\x1aavgFleetUtilizationPercent\"\xa8\x01\n" +
	"\fFailureEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"B\n" +
	"\x0eFailureRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xf0\x01\n" +
	"\x15FailureReportResponse\x12;\n" +
	"\bfailures\x18\x01 \x03(\v2\x1f.analytics_service.FailureEventR\bfailures\x12%\n" +
	"\x0etotal_failures\x18\x02 \x01(\x05R\rtotalFailures\x12:\n" +
	"\x19charging_congestion_count\x18\x03 \x01(\x05R\x17chargingCongestionCount\x127\n" +
	"\x18low_battery_alerts_count\x18\x04 \x01(\x05R\x15lowBatteryAlertsCount2\xa1\x03\n" +
	"\x10AnalyticsService\x12b\n" +
	"\x0fGetFleetMetrics\x12&.analytics_service.FleetMetricsRequest\x1a'.analytics_service.FleetMetricsResponse\x12b\n" +
	"\x0fGetOrderMetrics\x12&.analytics_service.OrderMetricsRequest\x1a'.analytics_service.OrderMetricsResponse\x12d\n" +
	"\x13GetDroneUtilization\x12%.analytics_service.UtilizationRequest\x1a&.analytics_service.UtilizationResponse\x12_\n" +
	"\x10GetFailureReport\x12!.analytics_service.FailureRequest\x1a(.analytics_service.FailureReportResponseBPZNgithub.com/RevenueIQ/revenueiq_dev_kit/proto/analytics_service;analytics_protob\x06proto3"

var (
	file_proto_analytics_service_analytics_service_proto_rawDescOnce sync.Once
	file_proto_analytics_service_analytics_service_proto_rawDescData []byte
)

func file_proto_analytics_service_analytics_service_proto_rawDescGZIP() []byte {
	file_proto_analytics_service_analytics_service_proto_rawDescOnce.Do(func() {
		file_proto_analytics_service_analytics_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_service_analytics_service_proto_rawDesc), len(file_proto_analytics_service_analytics_service_proto_rawDesc)))
	})
	return file_proto_analytics_service_analytics_service_proto_rawDescData
}

var file_proto_analytics_service_analytics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_analytics_service_analytics_service_proto_goTypes = []any{
	(*FleetMetricsRequest)(nil),   // 0: analytics_service.FleetMetricsRequest
	(*FleetMetricsResponse)(nil),  // 1: analytics_service.FleetMetricsResponse
	(*OrderMetricsRequest)(nil),   // 2: analytics_service.OrderMetricsRequest
	(*OrderMetricsResponse)(nil),  // 3: analytics_service.OrderMetricsResponse
	(*UtilizationRequest)(nil),    // 4: analytics_service.UtilizationRequest
	(*DroneStats)(nil),            // 5: analytics_service.DroneStats
	(*UtilizationResponse)(nil),   // 6: analytics_service.UtilizationResponse
	(*FailureEvent)(nil),          // 7: analytics_service.FailureEvent
	(*FailureRequest)(nil),        // 8: analytics_service.FailureRequest
	(*FailureReportResponse)(nil), // 9: analytics_service.FailureReportResponse
}
var file_proto_analytics_service_analytics_service_proto_depIdxs = []int32{
	5, // 0: analytics_service.UtilizationResponse.drones:type_name -> analytics_service.DroneStats
	7, // 1: analytics_service.FailureReportResponse.failures:type_name -> analytics_service.FailureEvent
	0, // 2: analytics_service.AnalyticsService.GetFleetMetrics:input_type -> analytics_service.FleetMetricsRequest
	2, // 3: analytics_service.AnalyticsService.GetOrderMetrics:input_type -> analytics_service.OrderMetricsRequest
	4, // 4: analytics_service.AnalyticsService.GetDroneUtilization:input_type -> analytics_service.UtilizationRequest
	8, // 5: analytics_service.AnalyticsService.GetFailureReport:input_type -> analytics_service.FailureRequest
	1, // 6: analytics_service.AnalyticsService.GetFleetMetrics:output_type -> analytics_service.FleetMetricsResponse
	3, // 7: analytics_service.AnalyticsService.GetOrderMetrics:output_type -> analytics_service.OrderMetricsResponse
	6, // 8: analytics_service.AnalyticsService.GetDroneUtilization:output_type -> analytics_service.UtilizationResponse
	9, // 9: analytics_service.AnalyticsService.GetFailureReport:output_type -> analytics_service.FailureReportResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_analytics_service_analytics_service_proto_init() }
func file_proto_analytics_service_analytics_service_proto_init() {
	if File_proto_analytics_service_analytics_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_service_analytics_service_proto_rawDesc), len(file_proto_analytics_service_analytics_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_service_analytics_service_proto_goTypes,
		DependencyIndexes: file_proto_analytics_service_analytics_service_proto_depIdxs,
		MessageInfos:      file_proto_analytics_service_analytics_service_proto_msgTypes,
	}.Build()
	File_proto_analytics_service_analytics_service_proto = out.File
	file_proto_analytics_service_analytics_service_proto_goTypes = nil
	file_proto_analytics_service_analytics_service_proto_depIdxs = nil
}
