// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/recovery/recovery.proto

package recovery_proto

import (
	common "github.com/RevenueIQ/revenueiq_dev_kit/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecoveryAction int32

const (
	RecoveryAction_ACTION_UNKNOWN               RecoveryAction = 0
	RecoveryAction_ACTION_RETRY_PAYMENT         RecoveryAction = 1
	RecoveryAction_ACTION_CREATE_PAYMENT_LINK   RecoveryAction = 2
	RecoveryAction_ACTION_SEND_REMINDER_EMAIL   RecoveryAction = 3
	RecoveryAction_ACTION_WAIT_AND_RETRY        RecoveryAction = 4
	RecoveryAction_ACTION_ESCALATE_TO_HUMAN     RecoveryAction = 5
	RecoveryAction_ACTION_ABANDON               RecoveryAction = 6
	RecoveryAction_ACTION_RETRY_SUBSCRIPTION    RecoveryAction = 7
	RecoveryAction_ACTION_SEND_CARD_UPDATE_LINK RecoveryAction = 8
	RecoveryAction_ACTION_RENEW_MANDATE         RecoveryAction = 9
	RecoveryAction_ACTION_VOICE_CALL            RecoveryAction = 10
	RecoveryAction_ACTION_CHECKOUT_NUDGE        RecoveryAction = 11
	RecoveryAction_ACTION_PROMISE_FOLLOW_UP     RecoveryAction = 12
)

// Enum value maps for RecoveryAction.
var (
	RecoveryAction_name = map[int32]string{
		0:  "ACTION_UNKNOWN",
		1:  "ACTION_RETRY_PAYMENT",
		2:  "ACTION_CREATE_PAYMENT_LINK",
		3:  "ACTION_SEND_REMINDER_EMAIL",
		4:  "ACTION_WAIT_AND_RETRY",
		5:  "ACTION_ESCALATE_TO_HUMAN",
		6:  "ACTION_ABANDON",
		7:  "ACTION_RETRY_SUBSCRIPTION",
		8:  "ACTION_SEND_CARD_UPDATE_LINK",
		9:  "ACTION_RENEW_MANDATE",
		10: "ACTION_VOICE_CALL",
		11: "ACTION_CHECKOUT_NUDGE",
		12: "ACTION_PROMISE_FOLLOW_UP",
	}
	RecoveryAction_value = map[string]int32{
		"ACTION_UNKNOWN":               0,
		"ACTION_RETRY_PAYMENT":         1,
		"ACTION_CREATE_PAYMENT_LINK":   2,
		"ACTION_SEND_REMINDER_EMAIL":   3,
		"ACTION_WAIT_AND_RETRY":        4,
		"ACTION_ESCALATE_TO_HUMAN":     5,
		"ACTION_ABANDON":               6,
		"ACTION_RETRY_SUBSCRIPTION":    7,
		"ACTION_SEND_CARD_UPDATE_LINK": 8,
		"ACTION_RENEW_MANDATE":         9,
		"ACTION_VOICE_CALL":            10,
		"ACTION_CHECKOUT_NUDGE":        11,
		"ACTION_PROMISE_FOLLOW_UP":     12,
	}
)

func (x RecoveryAction) Enum() *RecoveryAction {
	p := new(RecoveryAction)
	*p = x
	return p
}

func (x RecoveryAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recovery_recovery_proto_enumTypes[0].Descriptor()
}

func (RecoveryAction) Type() protoreflect.EnumType {
	return &file_proto_recovery_recovery_proto_enumTypes[0]
}

func (x RecoveryAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryAction.Descriptor instead.
func (RecoveryAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{0}
}

type WorkflowStatus int32

const (
	WorkflowStatus_WF_CREATED     WorkflowStatus = 0
	WorkflowStatus_WF_IN_PROGRESS WorkflowStatus = 1
	WorkflowStatus_WF_RECOVERED   WorkflowStatus = 2
	WorkflowStatus_WF_FAILED      WorkflowStatus = 3
	WorkflowStatus_WF_ABANDONED   WorkflowStatus = 4
	WorkflowStatus_WF_ESCALATED   WorkflowStatus = 5
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WF_CREATED",
		1: "WF_IN_PROGRESS",
		2: "WF_RECOVERED",
		3: "WF_FAILED",
		4: "WF_ABANDONED",
		5: "WF_ESCALATED",
	}
	WorkflowStatus_value = map[string]int32{
		"WF_CREATED":     0,
		"WF_IN_PROGRESS": 1,
		"WF_RECOVERED":   2,
		"WF_FAILED":      3,
		"WF_ABANDONED":   4,
		"WF_ESCALATED":   5,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recovery_recovery_proto_enumTypes[1].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_proto_recovery_recovery_proto_enumTypes[1]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{1}
}

type CreateWorkflowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FailureId       string                 `protobuf:"bytes,2,opt,name=failure_id,json=failureId,proto3" json:"failure_id,omitempty"`
	PaymentId       string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	DiagnosisId     string                 `protobuf:"bytes,4,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount          *common.Money          `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	SuggestedAction string                 `protobuf:"bytes,9,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkflowRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetFailureId() string {
	if x != nil {
		return x.FailureId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetDiagnosisId() string {
	if x != nil {
		return x.DiagnosisId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateWorkflowRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateWorkflowRequest) GetSuggestedAction() string {
	if x != nil {
		return x.SuggestedAction
	}
	return ""
}

type RecoveryWorkflow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             *common.StatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	WorkflowId         string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	FailureId          string                 `protobuf:"bytes,3,opt,name=failure_id,json=failureId,proto3" json:"failure_id,omitempty"`
	PaymentId          string                 `protobuf:"bytes,4,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount             *common.Money          `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	WorkflowStatus     WorkflowStatus         `protobuf:"varint,6,opt,name=workflow_status,json=workflowStatus,proto3,enum=revenueiq.recovery.WorkflowStatus" json:"workflow_status,omitempty"`
	Steps              []*RecoveryStep        `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	RetryCount         int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ContactCount       int32                  `protobuf:"varint,9,opt,name=contact_count,json=contactCount,proto3" json:"contact_count,omitempty"`
	RecoveryCost       *common.Money          `protobuf:"bytes,10,opt,name=recovery_cost,json=recoveryCost,proto3" json:"recovery_cost,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RecoveredPaymentId string                 `protobuf:"bytes,13,opt,name=recovered_payment_id,json=recoveredPaymentId,proto3" json:"recovered_payment_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecoveryWorkflow) Reset() {
	*x = RecoveryWorkflow{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryWorkflow) ProtoMessage() {}

func (x *RecoveryWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryWorkflow.ProtoReflect.Descriptor instead.
func (*RecoveryWorkflow) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *RecoveryWorkflow) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RecoveryWorkflow) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecoveryWorkflow) GetFailureId() string {
	if x != nil {
		return x.FailureId
	}
	return ""
}

func (x *RecoveryWorkflow) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RecoveryWorkflow) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RecoveryWorkflow) GetWorkflowStatus() WorkflowStatus {
	if x != nil {
		return x.WorkflowStatus
	}
	return WorkflowStatus_WF_CREATED
}

func (x *RecoveryWorkflow) GetSteps() []*RecoveryStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RecoveryWorkflow) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *RecoveryWorkflow) GetContactCount() int32 {
	if x != nil {
		return x.ContactCount
	}
	return 0
}

func (x *RecoveryWorkflow) GetRecoveryCost() *common.Money {
	if x != nil {
		return x.RecoveryCost
	}
	return nil
}

func (x *RecoveryWorkflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecoveryWorkflow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RecoveryWorkflow) GetRecoveredPaymentId() string {
	if x != nil {
		return x.RecoveredPaymentId
	}
	return ""
}

type RecoveryStep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StepId            string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Action            RecoveryAction         `protobuf:"varint,2,opt,name=action,proto3,enum=revenueiq.recovery.RecoveryAction" json:"action,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "PENDING" | "EXECUTING" | "SUCCESS" | "FAILED" | "SKIPPED"
	ResultDetail      string                 `protobuf:"bytes,4,opt,name=result_detail,json=resultDetail,proto3" json:"result_detail,omitempty"`
	AiReasoning       string                 `protobuf:"bytes,5,opt,name=ai_reasoning,json=aiReasoning,proto3" json:"ai_reasoning,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExecutedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	DurationMs        int32                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	GuardrailsChecked []string               `protobuf:"bytes,9,rep,name=guardrails_checked,json=guardrailsChecked,proto3" json:"guardrails_checked,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecoveryStep) Reset() {
	*x = RecoveryStep{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStep) ProtoMessage() {}

func (x *RecoveryStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStep.ProtoReflect.Descriptor instead.
func (*RecoveryStep) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *RecoveryStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *RecoveryStep) GetAction() RecoveryAction {
	if x != nil {
		return x.Action
	}
	return RecoveryAction_ACTION_UNKNOWN
}

func (x *RecoveryStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecoveryStep) GetResultDetail() string {
	if x != nil {
		return x.ResultDetail
	}
	return ""
}

func (x *RecoveryStep) GetAiReasoning() string {
	if x != nil {
		return x.AiReasoning
	}
	return ""
}

func (x *RecoveryStep) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecoveryStep) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *RecoveryStep) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecoveryStep) GetGuardrailsChecked() []string {
	if x != nil {
		return x.GuardrailsChecked
	}
	return nil
}

type ExecuteStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepRequest) Reset() {
	*x = ExecuteStepRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepRequest) ProtoMessage() {}

func (x *ExecuteStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStepRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteStepRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteStepRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type StepResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            *common.StatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Step              *RecoveryStep          `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	NewWorkflowStatus WorkflowStatus         `protobuf:"varint,3,opt,name=new_workflow_status,json=newWorkflowStatus,proto3,enum=revenueiq.recovery.WorkflowStatus" json:"new_workflow_status,omitempty"`
	NextAction        string                 `protobuf:"bytes,4,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{4}
}

func (x *StepResult) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StepResult) GetStep() *RecoveryStep {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *StepResult) GetNewWorkflowStatus() WorkflowStatus {
	if x != nil {
		return x.NewWorkflowStatus
	}
	return WorkflowStatus_WF_CREATED
}

func (x *StepResult) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RequestId     string                    `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerchantId    string                    `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Status        WorkflowStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=revenueiq.recovery.WorkflowStatus" json:"status,omitempty"`
	TimeRange     *common.TimeRange         `protobuf:"bytes,4,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListWorkflowsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListWorkflowsRequest) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WF_CREATED
}

func (x *ListWorkflowsRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListWorkflowsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        *common.StatusResponse     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Workflows     []*RecoveryWorkflow        `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkflowsResponse) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListWorkflowsResponse) GetWorkflows() []*RecoveryWorkflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type RecoveryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryStatsRequest) Reset() {
	*x = RecoveryStatsRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStatsRequest) ProtoMessage() {}

func (x *RecoveryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStatsRequest.ProtoReflect.Descriptor instead.
func (*RecoveryStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{8}
}

func (x *RecoveryStatsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecoveryStatsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RecoveryStatsRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type RecoveryStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               *common.StatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalAtRisk          *common.Money          `protobuf:"bytes,2,opt,name=total_at_risk,json=totalAtRisk,proto3" json:"total_at_risk,omitempty"`
	TotalRecovered       *common.Money          `protobuf:"bytes,3,opt,name=total_recovered,json=totalRecovered,proto3" json:"total_recovered,omitempty"`
	TotalCost            *common.Money          `protobuf:"bytes,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	RecoveryRate         float32                `protobuf:"fixed32,5,opt,name=recovery_rate,json=recoveryRate,proto3" json:"recovery_rate,omitempty"`
	TotalWorkflows       int32                  `protobuf:"varint,6,opt,name=total_workflows,json=totalWorkflows,proto3" json:"total_workflows,omitempty"`
	ByStatus             map[string]int32       `protobuf:"bytes,7,rep,name=by_status,json=byStatus,proto3" json:"by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByAction             map[string]int32       `protobuf:"bytes,8,rep,name=by_action,json=byAction,proto3" json:"by_action,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RecoveryRateByMethod map[string]float32     `protobuf:"bytes,9,rep,name=recovery_rate_by_method,json=recoveryRateByMethod,proto3" json:"recovery_rate_by_method,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecoveryStats) Reset() {
	*x = RecoveryStats{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStats) ProtoMessage() {}

func (x *RecoveryStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStats.ProtoReflect.Descriptor instead.
func (*RecoveryStats) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{9}
}

func (x *RecoveryStats) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RecoveryStats) GetTotalAtRisk() *common.Money {
	if x != nil {
		return x.TotalAtRisk
	}
	return nil
}

func (x *RecoveryStats) GetTotalRecovered() *common.Money {
	if x != nil {
		return x.TotalRecovered
	}
	return nil
}

func (x *RecoveryStats) GetTotalCost() *common.Money {
	if x != nil {
		return x.TotalCost
	}
	return nil
}

func (x *RecoveryStats) GetRecoveryRate() float32 {
	if x != nil {
		return x.RecoveryRate
	}
	return 0
}

func (x *RecoveryStats) GetTotalWorkflows() int32 {
	if x != nil {
		return x.TotalWorkflows
	}
	return 0
}

func (x *RecoveryStats) GetByStatus() map[string]int32 {
	if x != nil {
		return x.ByStatus
	}
	return nil
}

func (x *RecoveryStats) GetByAction() map[string]int32 {
	if x != nil {
		return x.ByAction
	}
	return nil
}

func (x *RecoveryStats) GetRecoveryRateByMethod() map[string]float32 {
	if x != nil {
		return x.RecoveryRateByMethod
	}
	return nil
}

type CreatePromiseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PromisedDate  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=promised_date,json=promisedDate,proto3" json:"promised_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromiseRequest) Reset() {
	*x = CreatePromiseRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromiseRequest) ProtoMessage() {}

func (x *CreatePromiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromiseRequest.ProtoReflect.Descriptor instead.
func (*CreatePromiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePromiseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreatePromiseRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CreatePromiseRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePromiseRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreatePromiseRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePromiseRequest) GetPromisedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PromisedDate
	}
	return nil
}

type Promise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.StatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PromiseId     string                 `protobuf:"bytes,2,opt,name=promise_id,json=promiseId,proto3" json:"promise_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	PromisedDate  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=promised_date,json=promisedDate,proto3" json:"promised_date,omitempty"`
	PromiseStatus string                 `protobuf:"bytes,8,opt,name=promise_status,json=promiseStatus,proto3" json:"promise_status,omitempty"` // "KEPT" | "BROKEN" | "PENDING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promise) Reset() {
	*x = Promise{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promise) ProtoMessage() {}

func (x *Promise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promise.ProtoReflect.Descriptor instead.
func (*Promise) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{11}
}

func (x *Promise) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Promise) GetPromiseId() string {
	if x != nil {
		return x.PromiseId
	}
	return ""
}

func (x *Promise) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Promise) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Promise) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Promise) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Promise) GetPromisedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PromisedDate
	}
	return nil
}

func (x *Promise) GetPromiseStatus() string {
	if x != nil {
		return x.PromiseStatus
	}
	return ""
}

type GetPromiseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PromiseId     string                 `protobuf:"bytes,2,opt,name=promise_id,json=promiseId,proto3" json:"promise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromiseRequest) Reset() {
	*x = GetPromiseRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromiseRequest) ProtoMessage() {}

func (x *GetPromiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromiseRequest.ProtoReflect.Descriptor instead.
func (*GetPromiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{12}
}

func (x *GetPromiseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetPromiseRequest) GetPromiseId() string {
	if x != nil {
		return x.PromiseId
	}
	return ""
}

type ListPromisesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RequestId     string                    `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerchantId    string                    `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromisesRequest) Reset() {
	*x = ListPromisesRequest{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromisesRequest) ProtoMessage() {}

func (x *ListPromisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromisesRequest.ProtoReflect.Descriptor instead.
func (*ListPromisesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{13}
}

func (x *ListPromisesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListPromisesRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListPromisesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPromisesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        *common.StatusResponse     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Promises      []*Promise                 `protobuf:"bytes,2,rep,name=promises,proto3" json:"promises,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromisesResponse) Reset() {
	*x = ListPromisesResponse{}
	mi := &file_proto_recovery_recovery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromisesResponse) ProtoMessage() {}

func (x *ListPromisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recovery_recovery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromisesResponse.ProtoReflect.Descriptor instead.
func (*ListPromisesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recovery_recovery_proto_rawDescGZIP(), []int{14}
}

func (x *ListPromisesResponse) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListPromisesResponse) GetPromises() []*Promise {
	if x != nil {
		return x.Promises
	}
	return nil
}

func (x *ListPromisesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_recovery_recovery_proto protoreflect.FileDescriptor

const file_proto_recovery_recovery_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/recovery/recovery.proto\x12\x12revenueiq.recovery\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xdc\x02\n" +
	"\x15CreateWorkflowRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"failure_id\x18\x02 \x01(\tR\tfailureId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12!\n" +
	"\fdiagnosis_id\x18\x04 \x01(\tR\vdiagnosisId\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\tR\n" +
	"merchantId\x12/\n" +
	"\x06amount\x18\a \x01(\v2\x17.revenueiq.common.MoneyR\x06amount\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10suggested_action\x18\t \x01(\tR\x0fsuggestedAction\"\x8d\x05\n" +
	"\x10RecoveryWorkflow\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"failure_id\x18\x03 \x01(\tR\tfailureId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x04 \x01(\tR\tpaymentId\x12/\n" +
	"\x06amount\x18\x05 \x01(\v2\x17.revenueiq.common.MoneyR\x06amount\x12K\n" +
	"\x0fworkflow_status\x18\x06 \x01(\x0e2\".revenueiq.recovery.WorkflowStatusR\x0eworkflowStatus\x126\n" +
	"\x05steps\x18\a \x03(\v2 .revenueiq.recovery.RecoveryStepR\x05steps\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rcontact_count\x18\t \x01(\x05R\fcontactCount\x12<\n" +
	"\rrecovery_cost\x18\n" +
	" \x01(\v2\x17.revenueiq.common.MoneyR\frecoveryCost\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x14recovered_payment_id\x18\r \x01(\tR\x12recoveredPaymentId\"\xd9\x03\n" +
	"\fRecoveryStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12:\n" +
	"\x06action\x18\x02 \x01(\x0e2\".revenueiq.recovery.RecoveryActionR\x06action\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rresult_detail\x18\x04 \x01(\tR\fresultDetail\x12!\n" +
	"\fai_reasoning\x18\x05 \x01(\tR\vaiReasoning\x12J\n" +
	"\bmetadata\x18\x06 \x03(\v2..revenueiq.recovery.RecoveryStep.MetadataEntryR\bmetadata\x12;\n" +
	"\vexecuted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\x12-\n" +
	"\x12guardrails_checked\x18\t \x03(\tR\x11guardrailsChecked\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x12ExecuteStepRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\"\xf1\x01\n" +
	"\n" +
	"StepResult\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x124\n" +
	"\x04step\x18\x02 \x01(\v2 .revenueiq.recovery.RecoveryStepR\x04step\x12R\n" +
	"\x13new_workflow_status\x18\x03 \x01(\x0e2\".revenueiq.recovery.WorkflowStatusR\x11newWorkflowStatus\x12\x1f\n" +
	"\vnext_action\x18\x04 \x01(\tR\n" +
	"nextAction\"T\n" +
	"\x12GetWorkflowRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\"\x93\x02\n" +
	"\x14ListWorkflowsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".revenueiq.recovery.WorkflowStatusR\x06status\x12:\n" +
	"\n" +
	"time_range\x18\x04 \x01(\v2\x1b.revenueiq.common.TimeRangeR\ttimeRange\x12C\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2#.revenueiq.common.PaginationRequestR\n" +
	"pagination\"\xdb\x01\n" +
	"\x15ListWorkflowsResponse\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x12B\n" +
	"\tworkflows\x18\x02 \x03(\v2$.revenueiq.recovery.RecoveryWorkflowR\tworkflows\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.revenueiq.common.PaginationResponseR\n" +
	"pagination\"\x92\x01\n" +
	"\x14RecoveryStatsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12:\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x1b.revenueiq.common.TimeRangeR\ttimeRange\"\xa1\x06\n" +
	"\rRecoveryStats\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x12;\n" +
	"\rtotal_at_risk\x18\x02 \x01(\v2\x17.revenueiq.common.MoneyR\vtotalAtRisk\x12@\n" +
	"\x0ftotal_recovered\x18\x03 \x01(\v2\x17.revenueiq.common.MoneyR\x0etotalRecovered\x126\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\v2\x17.revenueiq.common.MoneyR\ttotalCost\x12#\n" +
	"\rrecovery_rate\x18\x05 \x01(\x02R\frecoveryRate\x12'\n" +
	"\x0ftotal_workflows\x18\x06 \x01(\x05R\x0etotalWorkflows\x12L\n" +
	"\tby_status\x18\a \x03(\v2/.revenueiq.recovery.RecoveryStats.ByStatusEntryR\bbyStatus\x12L\n" +
	"\tby_action\x18\b \x03(\v2/.revenueiq.recovery.RecoveryStats.ByActionEntryR\bbyAction\x12r\n" +
	"\x17recovery_rate_by_method\x18\t \x03(\v2;.revenueiq.recovery.RecoveryStats.RecoveryRateByMethodEntryR\x14recoveryRateByMethod\x1a;\n" +
	"\rByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a;\n" +
	"\rByActionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aG\n" +
	"\x19RecoveryRateByMethodEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x8a\x02\n" +
	"\x14CreatePromiseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12/\n" +
	"\x06amount\x18\x05 \x01(\v2\x17.revenueiq.common.MoneyR\x06amount\x12?\n" +
	"\rpromised_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fpromisedDate\"\xde\x02\n" +
	"\aPromise\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x12\x1d\n" +
	"\n" +
	"promise_id\x18\x02 \x01(\tR\tpromiseId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12/\n" +
	"\x06amount\x18\x06 \x01(\v2\x17.revenueiq.common.MoneyR\x06amount\x12?\n" +
	"\rpromised_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fpromisedDate\x12%\n" +
	"\x0epromise_status\x18\b \x01(\tR\rpromiseStatus\"Q\n" +
	"\x11GetPromiseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"promise_id\x18\x02 \x01(\tR\tpromiseId\"\x9a\x01\n" +
	"\x13ListPromisesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12C\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2#.revenueiq.common.PaginationRequestR\n" +
	"pagination\"\xcf\x01\n" +
	"\x14ListPromisesResponse\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x127\n" +
	"\bpromises\x18\x02 \x03(\v2\x1b.revenueiq.recovery.PromiseR\bpromises\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.revenueiq.common.PaginationResponseR\n" +
	"pagination*\xf6\x02\n" +
	"\x0eRecoveryAction\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ACTION_RETRY_PAYMENT\x10\x01\x12\x1e\n" +
	"\x1aACTION_CREATE_PAYMENT_LINK\x10\x02\x12\x1e\n" +
	"\x1aACTION_SEND_REMINDER_EMAIL\x10\x03\x12\x19\n" +
	"\x15ACTION_WAIT_AND_RETRY\x10\x04\x12\x1c\n" +
	"\x18ACTION_ESCALATE_TO_HUMAN\x10\x05\x12\x12\n" +
	"\x0eACTION_ABANDON\x10\x06\x12\x1d\n" +
	"\x19ACTION_RETRY_SUBSCRIPTION\x10\a\x12 \n" +
	"\x1cACTION_SEND_CARD_UPDATE_LINK\x10\b\x12\x18\n" +
	"\x14ACTION_RENEW_MANDATE\x10\t\x12\x15\n" +
	"\x11ACTION_VOICE_CALL\x10\n" +
	"\x12\x19\n" +
	"\x15ACTION_CHECKOUT_NUDGE\x10\v\x12\x1c\n" +
	"\x18ACTION_PROMISE_FOLLOW_UP\x10\f*y\n" +
	"\x0eWorkflowStatus\x12\x0e\n" +
	"\n" +
	"WF_CREATED\x10\x00\x12\x12\n" +
	"\x0eWF_IN_PROGRESS\x10\x01\x12\x10\n" +
	"\fWF_RECOVERED\x10\x02\x12\r\n" +
	"\tWF_FAILED\x10\x03\x12\x10\n" +
	"\fWF_ABANDONED\x10\x04\x12\x10\n" +
	"\fWF_ESCALATED\x10\x052\x80\x06\n" +
	"\x0fRecoveryService\x12a\n" +
	"\x0eCreateWorkflow\x12).revenueiq.recovery.CreateWorkflowRequest\x1a$.revenueiq.recovery.RecoveryWorkflow\x12Y\n" +
	"\x0fExecuteNextStep\x12&.revenueiq.recovery.ExecuteStepRequest\x1a\x1e.revenueiq.recovery.StepResult\x12[\n" +
	"\vGetWorkflow\x12&.revenueiq.recovery.GetWorkflowRequest\x1a$.revenueiq.recovery.RecoveryWorkflow\x12d\n" +
	"\rListWorkflows\x12(.revenueiq.recovery.ListWorkflowsRequest\x1a).revenueiq.recovery.ListWorkflowsResponse\x12_\n" +
	"\x10GetRecoveryStats\x12(.revenueiq.recovery.RecoveryStatsRequest\x1a!.revenueiq.recovery.RecoveryStats\x12V\n" +
	"\rCreatePromise\x12(.revenueiq.recovery.CreatePromiseRequest\x1a\x1b.revenueiq.recovery.Promise\x12P\n" +
	"\n" +
	"GetPromise\x12%.revenueiq.recovery.GetPromiseRequest\x1a\x1b.revenueiq.recovery.Promise\x12a\n" +
	"\fListPromises\x12'.revenueiq.recovery.ListPromisesRequest\x1a(.revenueiq.recovery.ListPromisesResponseBFZDgithub.com/RevenueIQ/revenueiq_dev_kit/proto/recovery;recovery_protob\x06proto3"

var (
	file_proto_recovery_recovery_proto_rawDescOnce sync.Once
	file_proto_recovery_recovery_proto_rawDescData []byte
)

func file_proto_recovery_recovery_proto_rawDescGZIP() []byte {
	file_proto_recovery_recovery_proto_rawDescOnce.Do(func() {
		file_proto_recovery_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recovery_recovery_proto_rawDesc), len(file_proto_recovery_recovery_proto_rawDesc)))
	})
	return file_proto_recovery_recovery_proto_rawDescData
}

var file_proto_recovery_recovery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_recovery_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_recovery_recovery_proto_goTypes = []any{
	(RecoveryAction)(0),               // 0: revenueiq.recovery.RecoveryAction
	(WorkflowStatus)(0),               // 1: revenueiq.recovery.WorkflowStatus
	(*CreateWorkflowRequest)(nil),     // 2: revenueiq.recovery.CreateWorkflowRequest
	(*RecoveryWorkflow)(nil),          // 3: revenueiq.recovery.RecoveryWorkflow
	(*RecoveryStep)(nil),              // 4: revenueiq.recovery.RecoveryStep
	(*ExecuteStepRequest)(nil),        // 5: revenueiq.recovery.ExecuteStepRequest
	(*StepResult)(nil),                // 6: revenueiq.recovery.StepResult
	(*GetWorkflowRequest)(nil),        // 7: revenueiq.recovery.GetWorkflowRequest
	(*ListWorkflowsRequest)(nil),      // 8: revenueiq.recovery.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),     // 9: revenueiq.recovery.ListWorkflowsResponse
	(*RecoveryStatsRequest)(nil),      // 10: revenueiq.recovery.RecoveryStatsRequest
	(*RecoveryStats)(nil),             // 11: revenueiq.recovery.RecoveryStats
	(*CreatePromiseRequest)(nil),      // 12: revenueiq.recovery.CreatePromiseRequest
	(*Promise)(nil),                   // 13: revenueiq.recovery.Promise
	(*GetPromiseRequest)(nil),         // 14: revenueiq.recovery.GetPromiseRequest
	(*ListPromisesRequest)(nil),       // 15: revenueiq.recovery.ListPromisesRequest
	(*ListPromisesResponse)(nil),      // 16: revenueiq.recovery.ListPromisesResponse
	nil,                               // 17: revenueiq.recovery.RecoveryStep.MetadataEntry
	nil,                               // 18: revenueiq.recovery.RecoveryStats.ByStatusEntry
	nil,                               // 19: revenueiq.recovery.RecoveryStats.ByActionEntry
	nil,                               // 20: revenueiq.recovery.RecoveryStats.RecoveryRateByMethodEntry
	(*common.Money)(nil),              // 21: revenueiq.common.Money
	(*common.StatusResponse)(nil),     // 22: revenueiq.common.StatusResponse
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
	(*common.TimeRange)(nil),          // 24: revenueiq.common.TimeRange
	(*common.PaginationRequest)(nil),  // 25: revenueiq.common.PaginationRequest
	(*common.PaginationResponse)(nil), // 26: revenueiq.common.PaginationResponse
}
var file_proto_recovery_recovery_proto_depIdxs = []int32{
	21, // 0: revenueiq.recovery.CreateWorkflowRequest.amount:type_name -> revenueiq.common.Money
	22, // 1: revenueiq.recovery.RecoveryWorkflow.status:type_name -> revenueiq.common.StatusResponse
	21, // 2: revenueiq.recovery.RecoveryWorkflow.amount:type_name -> revenueiq.common.Money
	1,  // 3: revenueiq.recovery.RecoveryWorkflow.workflow_status:type_name -> revenueiq.recovery.WorkflowStatus
	4,  // 4: revenueiq.recovery.RecoveryWorkflow.steps:type_name -> revenueiq.recovery.RecoveryStep
	21, // 5: revenueiq.recovery.RecoveryWorkflow.recovery_cost:type_name -> revenueiq.common.Money
	23, // 6: revenueiq.recovery.RecoveryWorkflow.created_at:type_name -> google.protobuf.Timestamp
	23, // 7: revenueiq.recovery.RecoveryWorkflow.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: revenueiq.recovery.RecoveryStep.action:type_name -> revenueiq.recovery.RecoveryAction
	17, // 9: revenueiq.recovery.RecoveryStep.metadata:type_name -> revenueiq.recovery.RecoveryStep.MetadataEntry
	23, // 10: revenueiq.recovery.RecoveryStep.executed_at:type_name -> google.protobuf.Timestamp
	22, // 11: revenueiq.recovery.StepResult.status:type_name -> revenueiq.common.StatusResponse
	4,  // 12: revenueiq.recovery.StepResult.step:type_name -> revenueiq.recovery.RecoveryStep
	1,  // 13: revenueiq.recovery.StepResult.new_workflow_status:type_name -> revenueiq.recovery.WorkflowStatus
	1,  // 14: revenueiq.recovery.ListWorkflowsRequest.status:type_name -> revenueiq.recovery.WorkflowStatus
	24, // 15: revenueiq.recovery.ListWorkflowsRequest.time_range:type_name -> revenueiq.common.TimeRange
	25, // 16: revenueiq.recovery.ListWorkflowsRequest.pagination:type_name -> revenueiq.common.PaginationRequest
	22, // 17: revenueiq.recovery.ListWorkflowsResponse.status:type_name -> revenueiq.common.StatusResponse
	3,  // 18: revenueiq.recovery.ListWorkflowsResponse.workflows:type_name -> revenueiq.recovery.RecoveryWorkflow
	26, // 19: revenueiq.recovery.ListWorkflowsResponse.pagination:type_name -> revenueiq.common.PaginationResponse
	24, // 20: revenueiq.recovery.RecoveryStatsRequest.time_range:type_name -> revenueiq.common.TimeRange
	22, // 21: revenueiq.recovery.RecoveryStats.status:type_name -> revenueiq.common.StatusResponse
	21, // 22: revenueiq.recovery.RecoveryStats.total_at_risk:type_name -> revenueiq.common.Money
	21, // 23: revenueiq.recovery.RecoveryStats.total_recovered:type_name -> revenueiq.common.Money
	21, // 24: revenueiq.recovery.RecoveryStats.total_cost:type_name -> revenueiq.common.Money
	18, // 25: revenueiq.recovery.RecoveryStats.by_status:type_name -> revenueiq.recovery.RecoveryStats.ByStatusEntry
	19, // 26: revenueiq.recovery.RecoveryStats.by_action:type_name -> revenueiq.recovery.RecoveryStats.ByActionEntry
	20, // 27: revenueiq.recovery.RecoveryStats.recovery_rate_by_method:type_name -> revenueiq.recovery.RecoveryStats.RecoveryRateByMethodEntry
	21, // 28: revenueiq.recovery.CreatePromiseRequest.amount:type_name -> revenueiq.common.Money
	23, // 29: revenueiq.recovery.CreatePromiseRequest.promised_date:type_name -> google.protobuf.Timestamp
	22, // 30: revenueiq.recovery.Promise.status:type_name -> revenueiq.common.StatusResponse
	21, // 31: revenueiq.recovery.Promise.amount:type_name -> revenueiq.common.Money
	23, // 32: revenueiq.recovery.Promise.promised_date:type_name -> google.protobuf.Timestamp
	25, // 33: revenueiq.recovery.ListPromisesRequest.pagination:type_name -> revenueiq.common.PaginationRequest
	22, // 34: revenueiq.recovery.ListPromisesResponse.status:type_name -> revenueiq.common.StatusResponse
	13, // 35: revenueiq.recovery.ListPromisesResponse.promises:type_name -> revenueiq.recovery.Promise
	26, // 36: revenueiq.recovery.ListPromisesResponse.pagination:type_name -> revenueiq.common.PaginationResponse
	2,  // 37: revenueiq.recovery.RecoveryService.CreateWorkflow:input_type -> revenueiq.recovery.CreateWorkflowRequest
	5,  // 38: revenueiq.recovery.RecoveryService.ExecuteNextStep:input_type -> revenueiq.recovery.ExecuteStepRequest
	7,  // 39: revenueiq.recovery.RecoveryService.GetWorkflow:input_type -> revenueiq.recovery.GetWorkflowRequest
	8,  // 40: revenueiq.recovery.RecoveryService.ListWorkflows:input_type -> revenueiq.recovery.ListWorkflowsRequest
	10, // 41: revenueiq.recovery.RecoveryService.GetRecoveryStats:input_type -> revenueiq.recovery.RecoveryStatsRequest
	12, // 42: revenueiq.recovery.RecoveryService.CreatePromise:input_type -> revenueiq.recovery.CreatePromiseRequest
	14, // 43: revenueiq.recovery.RecoveryService.GetPromise:input_type -> revenueiq.recovery.GetPromiseRequest
	15, // 44: revenueiq.recovery.RecoveryService.ListPromises:input_type -> revenueiq.recovery.ListPromisesRequest
	3,  // 45: revenueiq.recovery.RecoveryService.CreateWorkflow:output_type -> revenueiq.recovery.RecoveryWorkflow
	6,  // 46: revenueiq.recovery.RecoveryService.ExecuteNextStep:output_type -> revenueiq.recovery.StepResult
	3,  // 47: revenueiq.recovery.RecoveryService.GetWorkflow:output_type -> revenueiq.recovery.RecoveryWorkflow
	9,  // 48: revenueiq.recovery.RecoveryService.ListWorkflows:output_type -> revenueiq.recovery.ListWorkflowsResponse
	11, // 49: revenueiq.recovery.RecoveryService.GetRecoveryStats:output_type -> revenueiq.recovery.RecoveryStats
	13, // 50: revenueiq.recovery.RecoveryService.CreatePromise:output_type -> revenueiq.recovery.Promise
	13, // 51: revenueiq.recovery.RecoveryService.GetPromise:output_type -> revenueiq.recovery.Promise
	16, // 52: revenueiq.recovery.RecoveryService.ListPromises:output_type -> revenueiq.recovery.ListPromisesResponse
	45, // [45:53] is the sub-list for method output_type
	37, // [37:45] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_proto_recovery_recovery_proto_init() }
func file_proto_recovery_recovery_proto_init() {
	if File_proto_recovery_recovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recovery_recovery_proto_rawDesc), len(file_proto_recovery_recovery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recovery_recovery_proto_goTypes,
		DependencyIndexes: file_proto_recovery_recovery_proto_depIdxs,
		EnumInfos:         file_proto_recovery_recovery_proto_enumTypes,
		MessageInfos:      file_proto_recovery_recovery_proto_msgTypes,
	}.Build()
	File_proto_recovery_recovery_proto = out.File
	file_proto_recovery_recovery_proto_goTypes = nil
	file_proto_recovery_recovery_proto_depIdxs = nil
}
