// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/s3_service/s3_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S3Service_Upload_FullMethodName      = "/s3_service.S3Service/Upload"
	S3Service_UploadUnary_FullMethodName = "/s3_service.S3Service/UploadUnary"
)

// S3ServiceClient is the client API for S3Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S3ServiceClient interface {
	// Uploads a file/object using client-side streaming.
	// Can be used for both single files and continuous IoT/live streams.
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
	// Unary upload for smaller payloads (up to the configured connection limit, e.g., 25MB).
	UploadUnary(ctx context.Context, in *UploadUnaryRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type s3ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewS3ServiceClient(cc grpc.ClientConnInterface) S3ServiceClient {
	return &s3ServiceClient{cc}
}

func (c *s3ServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &S3Service_ServiceDesc.Streams[0], S3Service_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3Service_UploadClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

func (c *s3ServiceClient) UploadUnary(ctx context.Context, in *UploadUnaryRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, S3Service_UploadUnary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S3ServiceServer is the server API for S3Service service.
// All implementations must embed UnimplementedS3ServiceServer
// for forward compatibility.
type S3ServiceServer interface {
	// Uploads a file/object using client-side streaming.
	// Can be used for both single files and continuous IoT/live streams.
	Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	// Unary upload for smaller payloads (up to the configured connection limit, e.g., 25MB).
	UploadUnary(context.Context, *UploadUnaryRequest) (*UploadResponse, error)
	mustEmbedUnimplementedS3ServiceServer()
}

// UnimplementedS3ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS3ServiceServer struct{}

func (UnimplementedS3ServiceServer) Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedS3ServiceServer) UploadUnary(context.Context, *UploadUnaryRequest) (*UploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadUnary not implemented")
}
func (UnimplementedS3ServiceServer) mustEmbedUnimplementedS3ServiceServer() {}
func (UnimplementedS3ServiceServer) testEmbeddedByValue()                   {}

// UnsafeS3ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S3ServiceServer will
// result in compilation errors.
type UnsafeS3ServiceServer interface {
	mustEmbedUnimplementedS3ServiceServer()
}

func RegisterS3ServiceServer(s grpc.ServiceRegistrar, srv S3ServiceServer) {
	// If the following call panics, it indicates UnimplementedS3ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S3Service_ServiceDesc, srv)
}

func _S3Service_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(S3ServiceServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3Service_UploadServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

func _S3Service_UploadUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadUnaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3ServiceServer).UploadUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3Service_UploadUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3ServiceServer).UploadUnary(ctx, req.(*UploadUnaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// S3Service_ServiceDesc is the grpc.ServiceDesc for S3Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S3Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s3_service.S3Service",
	HandlerType: (*S3ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadUnary",
			Handler:    _S3Service_UploadUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _S3Service_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/s3_service/s3_service.proto",
}
