// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/webhook/webhook.proto

package webhook_proto

import (
	common "github.com/RevenueIQ/revenueiq_dev_kit/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RazorpayEventId  string                 `protobuf:"bytes,2,opt,name=razorpay_event_id,json=razorpayEventId,proto3" json:"razorpay_event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "payment.failed", "payment.captured", etc.
	Payload          *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ReceivedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	SignatureValid   string                 `protobuf:"bytes,6,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`       // "VALID" | "INVALID" | "SKIPPED"
	ProcessingStatus string                 `protobuf:"bytes,7,opt,name=processing_status,json=processingStatus,proto3" json:"processing_status,omitempty"` // "RECEIVED" | "PROCESSING" | "PROCESSED" | "FAILED"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_proto_webhook_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_proto_webhook_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEvent) GetRazorpayEventId() string {
	if x != nil {
		return x.RazorpayEventId
	}
	return ""
}

func (x *WebhookEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WebhookEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookEvent) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *WebhookEvent) GetSignatureValid() string {
	if x != nil {
		return x.SignatureValid
	}
	return ""
}

func (x *WebhookEvent) GetProcessingStatus() string {
	if x != nil {
		return x.ProcessingStatus
	}
	return ""
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_webhook_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_webhook_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RequestId     string                    `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventType     string                    `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TimeRange     *common.TimeRange         `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_webhook_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_webhook_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ListEventsRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListEventsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListEventsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        *common.StatusResponse     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Events        []*WebhookEvent            `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_webhook_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_webhook_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsResponse) GetStatus() *common.StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListEventsResponse) GetEvents() []*WebhookEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_webhook_webhook_proto protoreflect.FileDescriptor

const file_proto_webhook_webhook_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/webhook/webhook.proto\x12\x11revenueiq.webhook\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19proto/common/common.proto\"\xaf\x02\n" +
	"\fWebhookEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11razorpay_event_id\x18\x02 \x01(\tR\x0frazorpayEventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12;\n" +
	"\vreceived_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12'\n" +
	"\x0fsignature_valid\x18\x06 \x01(\tR\x0esignatureValid\x12+\n" +
	"\x11processing_status\x18\a \x01(\tR\x10processingStatus\"K\n" +
	"\x0fGetEventRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"\xd2\x01\n" +
	"\x11ListEventsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12:\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x1b.revenueiq.common.TimeRangeR\ttimeRange\x12C\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2#.revenueiq.common.PaginationRequestR\n" +
	"pagination\"\xcd\x01\n" +
	"\x12ListEventsResponse\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .revenueiq.common.StatusResponseR\x06status\x127\n" +
	"\x06events\x18\x02 \x03(\v2\x1f.revenueiq.webhook.WebhookEventR\x06events\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.revenueiq.common.PaginationResponseR\n" +
	"pagination2\xca\x01\n" +
	"\x0eWebhookService\x12V\n" +
	"\x0fGetWebhookEvent\x12\".revenueiq.webhook.GetEventRequest\x1a\x1f.revenueiq.webhook.WebhookEvent\x12`\n" +
	"\x11ListWebhookEvents\x12$.revenueiq.webhook.ListEventsRequest\x1a%.revenueiq.webhook.ListEventsResponseBDZBgithub.com/RevenueIQ/revenueiq_dev_kit/proto/webhook;webhook_protob\x06proto3"

var (
	file_proto_webhook_webhook_proto_rawDescOnce sync.Once
	file_proto_webhook_webhook_proto_rawDescData []byte
)

func file_proto_webhook_webhook_proto_rawDescGZIP() []byte {
	file_proto_webhook_webhook_proto_rawDescOnce.Do(func() {
		file_proto_webhook_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_webhook_webhook_proto_rawDesc), len(file_proto_webhook_webhook_proto_rawDesc)))
	})
	return file_proto_webhook_webhook_proto_rawDescData
}

var file_proto_webhook_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_webhook_webhook_proto_goTypes = []any{
	(*WebhookEvent)(nil),              // 0: revenueiq.webhook.WebhookEvent
	(*GetEventRequest)(nil),           // 1: revenueiq.webhook.GetEventRequest
	(*ListEventsRequest)(nil),         // 2: revenueiq.webhook.ListEventsRequest
	(*ListEventsResponse)(nil),        // 3: revenueiq.webhook.ListEventsResponse
	(*structpb.Struct)(nil),           // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
	(*common.TimeRange)(nil),          // 6: revenueiq.common.TimeRange
	(*common.PaginationRequest)(nil),  // 7: revenueiq.common.PaginationRequest
	(*common.StatusResponse)(nil),     // 8: revenueiq.common.StatusResponse
	(*common.PaginationResponse)(nil), // 9: revenueiq.common.PaginationResponse
}
var file_proto_webhook_webhook_proto_depIdxs = []int32{
	4, // 0: revenueiq.webhook.WebhookEvent.payload:type_name -> google.protobuf.Struct
	5, // 1: revenueiq.webhook.WebhookEvent.received_at:type_name -> google.protobuf.Timestamp
	6, // 2: revenueiq.webhook.ListEventsRequest.time_range:type_name -> revenueiq.common.TimeRange
	7, // 3: revenueiq.webhook.ListEventsRequest.pagination:type_name -> revenueiq.common.PaginationRequest
	8, // 4: revenueiq.webhook.ListEventsResponse.status:type_name -> revenueiq.common.StatusResponse
	0, // 5: revenueiq.webhook.ListEventsResponse.events:type_name -> revenueiq.webhook.WebhookEvent
	9, // 6: revenueiq.webhook.ListEventsResponse.pagination:type_name -> revenueiq.common.PaginationResponse
	1, // 7: revenueiq.webhook.WebhookService.GetWebhookEvent:input_type -> revenueiq.webhook.GetEventRequest
	2, // 8: revenueiq.webhook.WebhookService.ListWebhookEvents:input_type -> revenueiq.webhook.ListEventsRequest
	0, // 9: revenueiq.webhook.WebhookService.GetWebhookEvent:output_type -> revenueiq.webhook.WebhookEvent
	3, // 10: revenueiq.webhook.WebhookService.ListWebhookEvents:output_type -> revenueiq.webhook.ListEventsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_webhook_webhook_proto_init() }
func file_proto_webhook_webhook_proto_init() {
	if File_proto_webhook_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_webhook_webhook_proto_rawDesc), len(file_proto_webhook_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_webhook_webhook_proto_goTypes,
		DependencyIndexes: file_proto_webhook_webhook_proto_depIdxs,
		MessageInfos:      file_proto_webhook_webhook_proto_msgTypes,
	}.Build()
	File_proto_webhook_webhook_proto = out.File
	file_proto_webhook_webhook_proto_goTypes = nil
	file_proto_webhook_webhook_proto_depIdxs = nil
}
