// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/reconciliation/reconciliation.proto

package reconciliation_proto

import (
	context "context"
	common "github.com/RevenueIQ/revenueiq_dev_kit/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReconciliationService_RunReconciliation_FullMethodName = "/revenueiq.reconciliation.ReconciliationService/RunReconciliation"
	ReconciliationService_GetReport_FullMethodName         = "/revenueiq.reconciliation.ReconciliationService/GetReport"
	ReconciliationService_ListExceptions_FullMethodName    = "/revenueiq.reconciliation.ReconciliationService/ListExceptions"
	ReconciliationService_ResolveException_FullMethodName  = "/revenueiq.reconciliation.ReconciliationService/ResolveException"
)

// ReconciliationServiceClient is the client API for ReconciliationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReconciliationServiceClient interface {
	RunReconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (*ReconciliationReport, error)
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*ReconciliationReport, error)
	ListExceptions(ctx context.Context, in *ListExceptionsRequest, opts ...grpc.CallOption) (*ExceptionList, error)
	ResolveException(ctx context.Context, in *ResolveExceptionRequest, opts ...grpc.CallOption) (*common.StatusResponse, error)
}

type reconciliationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReconciliationServiceClient(cc grpc.ClientConnInterface) ReconciliationServiceClient {
	return &reconciliationServiceClient{cc}
}

func (c *reconciliationServiceClient) RunReconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (*ReconciliationReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconciliationReport)
	err := c.cc.Invoke(ctx, ReconciliationService_RunReconciliation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationServiceClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*ReconciliationReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconciliationReport)
	err := c.cc.Invoke(ctx, ReconciliationService_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationServiceClient) ListExceptions(ctx context.Context, in *ListExceptionsRequest, opts ...grpc.CallOption) (*ExceptionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExceptionList)
	err := c.cc.Invoke(ctx, ReconciliationService_ListExceptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationServiceClient) ResolveException(ctx context.Context, in *ResolveExceptionRequest, opts ...grpc.CallOption) (*common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.StatusResponse)
	err := c.cc.Invoke(ctx, ReconciliationService_ResolveException_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReconciliationServiceServer is the server API for ReconciliationService service.
// All implementations must embed UnimplementedReconciliationServiceServer
// for forward compatibility.
type ReconciliationServiceServer interface {
	RunReconciliation(context.Context, *ReconciliationRequest) (*ReconciliationReport, error)
	GetReport(context.Context, *GetReportRequest) (*ReconciliationReport, error)
	ListExceptions(context.Context, *ListExceptionsRequest) (*ExceptionList, error)
	ResolveException(context.Context, *ResolveExceptionRequest) (*common.StatusResponse, error)
	mustEmbedUnimplementedReconciliationServiceServer()
}

// UnimplementedReconciliationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReconciliationServiceServer struct{}

func (UnimplementedReconciliationServiceServer) RunReconciliation(context.Context, *ReconciliationRequest) (*ReconciliationReport, error) {
	return nil, status.Error(codes.Unimplemented, "method RunReconciliation not implemented")
}
func (UnimplementedReconciliationServiceServer) GetReport(context.Context, *GetReportRequest) (*ReconciliationReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedReconciliationServiceServer) ListExceptions(context.Context, *ListExceptionsRequest) (*ExceptionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExceptions not implemented")
}
func (UnimplementedReconciliationServiceServer) ResolveException(context.Context, *ResolveExceptionRequest) (*common.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveException not implemented")
}
func (UnimplementedReconciliationServiceServer) mustEmbedUnimplementedReconciliationServiceServer() {}
func (UnimplementedReconciliationServiceServer) testEmbeddedByValue()                               {}

// UnsafeReconciliationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReconciliationServiceServer will
// result in compilation errors.
type UnsafeReconciliationServiceServer interface {
	mustEmbedUnimplementedReconciliationServiceServer()
}

func RegisterReconciliationServiceServer(s grpc.ServiceRegistrar, srv ReconciliationServiceServer) {
	// If the following call panics, it indicates UnimplementedReconciliationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReconciliationService_ServiceDesc, srv)
}

func _ReconciliationService_RunReconciliation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconciliationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).RunReconciliation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_RunReconciliation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).RunReconciliation(ctx, req.(*ReconciliationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconciliationService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconciliationService_ListExceptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExceptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).ListExceptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_ListExceptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).ListExceptions(ctx, req.(*ListExceptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconciliationService_ResolveException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).ResolveException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_ResolveException_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).ResolveException(ctx, req.(*ResolveExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReconciliationService_ServiceDesc is the grpc.ServiceDesc for ReconciliationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReconciliationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revenueiq.reconciliation.ReconciliationService",
	HandlerType: (*ReconciliationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunReconciliation",
			Handler:    _ReconciliationService_RunReconciliation_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _ReconciliationService_GetReport_Handler,
		},
		{
			MethodName: "ListExceptions",
			Handler:    _ReconciliationService_ListExceptions_Handler,
		},
		{
			MethodName: "ResolveException",
			Handler:    _ReconciliationService_ResolveException_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reconciliation/reconciliation.proto",
}
