// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/redis_service/redis_service.proto

package redis_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CacheItem represents the envelope stored in the Redis cache.
// It wraps the raw value with metadata like namespace and timing.
type CacheItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp (seconds)
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp (seconds), 0 means no expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheItem) Reset() {
	*x = CacheItem{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheItem) ProtoMessage() {}

func (x *CacheItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheItem.ProtoReflect.Descriptor instead.
func (*CacheItem) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{0}
}

func (x *CacheItem) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CacheItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CacheItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CacheItem) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 or negative means no expiration
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`                      // Optional namespace to segment cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // Optional namespace to search in
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Item          *CacheItem             `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"` // Returns the full envelope containing metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetItem() *CacheItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // Optional namespace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InvalidateNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // The namespace to invalidate/clear
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateNamespaceRequest) Reset() {
	*x = InvalidateNamespaceRequest{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateNamespaceRequest) ProtoMessage() {}

func (x *InvalidateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*InvalidateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{7}
}

func (x *InvalidateNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type InvalidateNamespaceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvalidatedCount int64                  `protobuf:"varint,1,opt,name=invalidated_count,json=invalidatedCount,proto3" json:"invalidated_count,omitempty"` // Number of keys removed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvalidateNamespaceResponse) Reset() {
	*x = InvalidateNamespaceResponse{}
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateNamespaceResponse) ProtoMessage() {}

func (x *InvalidateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_service_redis_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*InvalidateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_service_redis_service_proto_rawDescGZIP(), []int{8}
}

func (x *InvalidateNamespaceResponse) GetInvalidatedCount() int64 {
	if x != nil {
		return x.InvalidatedCount
	}
	return 0
}

var File_proto_redis_service_redis_service_proto protoreflect.FileDescriptor

const file_proto_redis_service_redis_service_proto_rawDesc = "" +
	"\n" +
	"'proto/redis_service/redis_service.proto\x12\rredis_service\x1a\x19google/protobuf/any.proto\"\x93\x01\n" +
	"\tCacheItem\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x89\x01\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"}\n" +
	"\vGetResponse\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12,\n" +
	"\x04item\x18\x03 \x01(\v2\x18.redis_service.CacheItemR\x04item\"?\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x1aInvalidateNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"J\n" +
	"\x1bInvalidateNamespaceResponse\x12+\n" +
	"\x11invalidated_count\x18\x01 \x01(\x03R\x10invalidatedCount2\xc4\x02\n" +
	"\x11RedisCacheService\x12<\n" +
	"\x03Set\x12\x19.redis_service.SetRequest\x1a\x1a.redis_service.SetResponse\x12<\n" +
	"\x03Get\x12\x19.redis_service.GetRequest\x1a\x1a.redis_service.GetResponse\x12E\n" +
	"\x06Delete\x12\x1c.redis_service.DeleteRequest\x1a\x1d.redis_service.DeleteResponse\x12l\n" +
	"\x13InvalidateNamespace\x12).redis_service.InvalidateNamespaceRequest\x1a*.redis_service.InvalidateNamespaceResponseBHZFgithub.com/RevenueIQ/revenueiq_dev_kit/proto/redis_service;redis_protob\x06proto3"

var (
	file_proto_redis_service_redis_service_proto_rawDescOnce sync.Once
	file_proto_redis_service_redis_service_proto_rawDescData []byte
)

func file_proto_redis_service_redis_service_proto_rawDescGZIP() []byte {
	file_proto_redis_service_redis_service_proto_rawDescOnce.Do(func() {
		file_proto_redis_service_redis_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redis_service_redis_service_proto_rawDesc), len(file_proto_redis_service_redis_service_proto_rawDesc)))
	})
	return file_proto_redis_service_redis_service_proto_rawDescData
}

var file_proto_redis_service_redis_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_redis_service_redis_service_proto_goTypes = []any{
	(*CacheItem)(nil),                   // 0: redis_service.CacheItem
	(*SetRequest)(nil),                  // 1: redis_service.SetRequest
	(*SetResponse)(nil),                 // 2: redis_service.SetResponse
	(*GetRequest)(nil),                  // 3: redis_service.GetRequest
	(*GetResponse)(nil),                 // 4: redis_service.GetResponse
	(*DeleteRequest)(nil),               // 5: redis_service.DeleteRequest
	(*DeleteResponse)(nil),              // 6: redis_service.DeleteResponse
	(*InvalidateNamespaceRequest)(nil),  // 7: redis_service.InvalidateNamespaceRequest
	(*InvalidateNamespaceResponse)(nil), // 8: redis_service.InvalidateNamespaceResponse
	(*anypb.Any)(nil),                   // 9: google.protobuf.Any
}
var file_proto_redis_service_redis_service_proto_depIdxs = []int32{
	9, // 0: redis_service.CacheItem.value:type_name -> google.protobuf.Any
	9, // 1: redis_service.SetRequest.value:type_name -> google.protobuf.Any
	9, // 2: redis_service.GetResponse.value:type_name -> google.protobuf.Any
	0, // 3: redis_service.GetResponse.item:type_name -> redis_service.CacheItem
	1, // 4: redis_service.RedisCacheService.Set:input_type -> redis_service.SetRequest
	3, // 5: redis_service.RedisCacheService.Get:input_type -> redis_service.GetRequest
	5, // 6: redis_service.RedisCacheService.Delete:input_type -> redis_service.DeleteRequest
	7, // 7: redis_service.RedisCacheService.InvalidateNamespace:input_type -> redis_service.InvalidateNamespaceRequest
	2, // 8: redis_service.RedisCacheService.Set:output_type -> redis_service.SetResponse
	4, // 9: redis_service.RedisCacheService.Get:output_type -> redis_service.GetResponse
	6, // 10: redis_service.RedisCacheService.Delete:output_type -> redis_service.DeleteResponse
	8, // 11: redis_service.RedisCacheService.InvalidateNamespace:output_type -> redis_service.InvalidateNamespaceResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_redis_service_redis_service_proto_init() }
func file_proto_redis_service_redis_service_proto_init() {
	if File_proto_redis_service_redis_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redis_service_redis_service_proto_rawDesc), len(file_proto_redis_service_redis_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redis_service_redis_service_proto_goTypes,
		DependencyIndexes: file_proto_redis_service_redis_service_proto_depIdxs,
		MessageInfos:      file_proto_redis_service_redis_service_proto_msgTypes,
	}.Build()
	File_proto_redis_service_redis_service_proto = out.File
	file_proto_redis_service_redis_service_proto_goTypes = nil
	file_proto_redis_service_redis_service_proto_depIdxs = nil
}
