// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/redis_service/redis_service.proto

package redis_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedisCacheService_Set_FullMethodName                 = "/redis_service.RedisCacheService/Set"
	RedisCacheService_Get_FullMethodName                 = "/redis_service.RedisCacheService/Get"
	RedisCacheService_Delete_FullMethodName              = "/redis_service.RedisCacheService/Delete"
	RedisCacheService_InvalidateNamespace_FullMethodName = "/redis_service.RedisCacheService/InvalidateNamespace"
)

// RedisCacheServiceClient is the client API for RedisCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisCacheServiceClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	InvalidateNamespace(ctx context.Context, in *InvalidateNamespaceRequest, opts ...grpc.CallOption) (*InvalidateNamespaceResponse, error)
}

type redisCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisCacheServiceClient(cc grpc.ClientConnInterface) RedisCacheServiceClient {
	return &redisCacheServiceClient{cc}
}

func (c *redisCacheServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, RedisCacheService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisCacheServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RedisCacheService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisCacheServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RedisCacheService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisCacheServiceClient) InvalidateNamespace(ctx context.Context, in *InvalidateNamespaceRequest, opts ...grpc.CallOption) (*InvalidateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateNamespaceResponse)
	err := c.cc.Invoke(ctx, RedisCacheService_InvalidateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisCacheServiceServer is the server API for RedisCacheService service.
// All implementations must embed UnimplementedRedisCacheServiceServer
// for forward compatibility.
type RedisCacheServiceServer interface {
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	InvalidateNamespace(context.Context, *InvalidateNamespaceRequest) (*InvalidateNamespaceResponse, error)
	mustEmbedUnimplementedRedisCacheServiceServer()
}

// UnimplementedRedisCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedisCacheServiceServer struct{}

func (UnimplementedRedisCacheServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedRedisCacheServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRedisCacheServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRedisCacheServiceServer) InvalidateNamespace(context.Context, *InvalidateNamespaceRequest) (*InvalidateNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvalidateNamespace not implemented")
}
func (UnimplementedRedisCacheServiceServer) mustEmbedUnimplementedRedisCacheServiceServer() {}
func (UnimplementedRedisCacheServiceServer) testEmbeddedByValue()                           {}

// UnsafeRedisCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisCacheServiceServer will
// result in compilation errors.
type UnsafeRedisCacheServiceServer interface {
	mustEmbedUnimplementedRedisCacheServiceServer()
}

func RegisterRedisCacheServiceServer(s grpc.ServiceRegistrar, srv RedisCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedRedisCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedisCacheService_ServiceDesc, srv)
}

func _RedisCacheService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisCacheServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisCacheService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisCacheServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisCacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisCacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisCacheService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisCacheServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisCacheService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisCacheServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisCacheService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisCacheServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisCacheService_InvalidateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisCacheServiceServer).InvalidateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisCacheService_InvalidateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisCacheServiceServer).InvalidateNamespace(ctx, req.(*InvalidateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisCacheService_ServiceDesc is the grpc.ServiceDesc for RedisCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redis_service.RedisCacheService",
	HandlerType: (*RedisCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _RedisCacheService_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RedisCacheService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RedisCacheService_Delete_Handler,
		},
		{
			MethodName: "InvalidateNamespace",
			Handler:    _RedisCacheService_InvalidateNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/redis_service/redis_service.proto",
}
