// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/mongo_service/mongodb_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName     = "/mongodb_service.UserService/CreateUser"
	UserService_GetUser_FullMethodName        = "/mongodb_service.UserService/GetUser"
	UserService_GetUserByEmail_FullMethodName = "/mongodb_service.UserService/GetUserByEmail"
	UserService_UpdateUser_FullMethodName     = "/mongodb_service.UserService/UpdateUser"
	UserService_DeleteUser_FullMethodName     = "/mongodb_service.UserService/DeleteUser"
	UserService_QueryUsers_FullMethodName     = "/mongodb_service.UserService/QueryUsers"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	QueryUsers(ctx context.Context, in *QueryUsersRequest, opts ...grpc.CallOption) (*QueryUsersResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, UserService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByEmailResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QueryUsers(ctx context.Context, in *QueryUsersRequest, opts ...grpc.CallOption) (*QueryUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUsersResponse)
	err := c.cc.Invoke(ctx, UserService_QueryUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserByEmailResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	QueryUsers(context.Context, *QueryUsersRequest) (*QueryUsersResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserByEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServiceServer) QueryUsers(context.Context, *QueryUsersRequest) (*QueryUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUsers not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QueryUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryUsers(ctx, req.(*QueryUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserService_GetUserByEmail_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "QueryUsers",
			Handler:    _UserService_QueryUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	OrderMongoService_CreateOrder_FullMethodName       = "/mongodb_service.OrderMongoService/CreateOrder"
	OrderMongoService_GetOrder_FullMethodName          = "/mongodb_service.OrderMongoService/GetOrder"
	OrderMongoService_UpdateOrderStatus_FullMethodName = "/mongodb_service.OrderMongoService/UpdateOrderStatus"
	OrderMongoService_ListOrders_FullMethodName        = "/mongodb_service.OrderMongoService/ListOrders"
)

// OrderMongoServiceClient is the client API for OrderMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderMongoServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateMongoOrderRequest, opts ...grpc.CallOption) (*MongoOrderResponse, error)
	GetOrder(ctx context.Context, in *GetMongoOrderRequest, opts ...grpc.CallOption) (*MongoOrderResponse, error)
	UpdateOrderStatus(ctx context.Context, in *UpdateMongoOrderStatusRequest, opts ...grpc.CallOption) (*MongoOrderResponse, error)
	ListOrders(ctx context.Context, in *ListMongoOrdersRequest, opts ...grpc.CallOption) (*ListMongoOrdersResponse, error)
}

type orderMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderMongoServiceClient(cc grpc.ClientConnInterface) OrderMongoServiceClient {
	return &orderMongoServiceClient{cc}
}

func (c *orderMongoServiceClient) CreateOrder(ctx context.Context, in *CreateMongoOrderRequest, opts ...grpc.CallOption) (*MongoOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoOrderResponse)
	err := c.cc.Invoke(ctx, OrderMongoService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderMongoServiceClient) GetOrder(ctx context.Context, in *GetMongoOrderRequest, opts ...grpc.CallOption) (*MongoOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoOrderResponse)
	err := c.cc.Invoke(ctx, OrderMongoService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderMongoServiceClient) UpdateOrderStatus(ctx context.Context, in *UpdateMongoOrderStatusRequest, opts ...grpc.CallOption) (*MongoOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoOrderResponse)
	err := c.cc.Invoke(ctx, OrderMongoService_UpdateOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderMongoServiceClient) ListOrders(ctx context.Context, in *ListMongoOrdersRequest, opts ...grpc.CallOption) (*ListMongoOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMongoOrdersResponse)
	err := c.cc.Invoke(ctx, OrderMongoService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderMongoServiceServer is the server API for OrderMongoService service.
// All implementations must embed UnimplementedOrderMongoServiceServer
// for forward compatibility.
type OrderMongoServiceServer interface {
	CreateOrder(context.Context, *CreateMongoOrderRequest) (*MongoOrderResponse, error)
	GetOrder(context.Context, *GetMongoOrderRequest) (*MongoOrderResponse, error)
	UpdateOrderStatus(context.Context, *UpdateMongoOrderStatusRequest) (*MongoOrderResponse, error)
	ListOrders(context.Context, *ListMongoOrdersRequest) (*ListMongoOrdersResponse, error)
	mustEmbedUnimplementedOrderMongoServiceServer()
}

// UnimplementedOrderMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderMongoServiceServer struct{}

func (UnimplementedOrderMongoServiceServer) CreateOrder(context.Context, *CreateMongoOrderRequest) (*MongoOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderMongoServiceServer) GetOrder(context.Context, *GetMongoOrderRequest) (*MongoOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderMongoServiceServer) UpdateOrderStatus(context.Context, *UpdateMongoOrderStatusRequest) (*MongoOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}
func (UnimplementedOrderMongoServiceServer) ListOrders(context.Context, *ListMongoOrdersRequest) (*ListMongoOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrderMongoServiceServer) mustEmbedUnimplementedOrderMongoServiceServer() {}
func (UnimplementedOrderMongoServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderMongoServiceServer will
// result in compilation errors.
type UnsafeOrderMongoServiceServer interface {
	mustEmbedUnimplementedOrderMongoServiceServer()
}

func RegisterOrderMongoServiceServer(s grpc.ServiceRegistrar, srv OrderMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderMongoService_ServiceDesc, srv)
}

func _OrderMongoService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMongoOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMongoServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMongoService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMongoServiceServer).CreateOrder(ctx, req.(*CreateMongoOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderMongoService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMongoServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMongoService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMongoServiceServer).GetOrder(ctx, req.(*GetMongoOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderMongoService_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMongoOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMongoServiceServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMongoService_UpdateOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMongoServiceServer).UpdateOrderStatus(ctx, req.(*UpdateMongoOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderMongoService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMongoOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMongoServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMongoService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMongoServiceServer).ListOrders(ctx, req.(*ListMongoOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderMongoService_ServiceDesc is the grpc.ServiceDesc for OrderMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.OrderMongoService",
	HandlerType: (*OrderMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderMongoService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderMongoService_GetOrder_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _OrderMongoService_UpdateOrderStatus_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderMongoService_ListOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	DroneMongoService_RegisterDrone_FullMethodName      = "/mongodb_service.DroneMongoService/RegisterDrone"
	DroneMongoService_GetDrone_FullMethodName           = "/mongodb_service.DroneMongoService/GetDrone"
	DroneMongoService_UpdateDroneStatus_FullMethodName  = "/mongodb_service.DroneMongoService/UpdateDroneStatus"
	DroneMongoService_FindAvailableDrone_FullMethodName = "/mongodb_service.DroneMongoService/FindAvailableDrone"
	DroneMongoService_ReserveDrone_FullMethodName       = "/mongodb_service.DroneMongoService/ReserveDrone"
	DroneMongoService_AssignDrone_FullMethodName        = "/mongodb_service.DroneMongoService/AssignDrone"
	DroneMongoService_ListDrones_FullMethodName         = "/mongodb_service.DroneMongoService/ListDrones"
)

// DroneMongoServiceClient is the client API for DroneMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneMongoServiceClient interface {
	RegisterDrone(ctx context.Context, in *RegisterMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error)
	GetDrone(ctx context.Context, in *GetMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error)
	UpdateDroneStatus(ctx context.Context, in *UpdateMongoDroneStatusRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error)
	FindAvailableDrone(ctx context.Context, in *FindAvailableDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error)
	ReserveDrone(ctx context.Context, in *ReserveMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error)
	AssignDrone(ctx context.Context, in *AssignMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error)
	ListDrones(ctx context.Context, in *ListMongoDronesRequest, opts ...grpc.CallOption) (*ListMongoDronesResponse, error)
}

type droneMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneMongoServiceClient(cc grpc.ClientConnInterface) DroneMongoServiceClient {
	return &droneMongoServiceClient{cc}
}

func (c *droneMongoServiceClient) RegisterDrone(ctx context.Context, in *RegisterMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDroneResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_RegisterDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneMongoServiceClient) GetDrone(ctx context.Context, in *GetMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDroneResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_GetDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneMongoServiceClient) UpdateDroneStatus(ctx context.Context, in *UpdateMongoDroneStatusRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDroneResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_UpdateDroneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneMongoServiceClient) FindAvailableDrone(ctx context.Context, in *FindAvailableDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDroneResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_FindAvailableDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneMongoServiceClient) ReserveDrone(ctx context.Context, in *ReserveMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDroneResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_ReserveDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneMongoServiceClient) AssignDrone(ctx context.Context, in *AssignMongoDroneRequest, opts ...grpc.CallOption) (*MongoDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDroneResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_AssignDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneMongoServiceClient) ListDrones(ctx context.Context, in *ListMongoDronesRequest, opts ...grpc.CallOption) (*ListMongoDronesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMongoDronesResponse)
	err := c.cc.Invoke(ctx, DroneMongoService_ListDrones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroneMongoServiceServer is the server API for DroneMongoService service.
// All implementations must embed UnimplementedDroneMongoServiceServer
// for forward compatibility.
type DroneMongoServiceServer interface {
	RegisterDrone(context.Context, *RegisterMongoDroneRequest) (*MongoDroneResponse, error)
	GetDrone(context.Context, *GetMongoDroneRequest) (*MongoDroneResponse, error)
	UpdateDroneStatus(context.Context, *UpdateMongoDroneStatusRequest) (*MongoDroneResponse, error)
	FindAvailableDrone(context.Context, *FindAvailableDroneRequest) (*MongoDroneResponse, error)
	ReserveDrone(context.Context, *ReserveMongoDroneRequest) (*MongoDroneResponse, error)
	AssignDrone(context.Context, *AssignMongoDroneRequest) (*MongoDroneResponse, error)
	ListDrones(context.Context, *ListMongoDronesRequest) (*ListMongoDronesResponse, error)
	mustEmbedUnimplementedDroneMongoServiceServer()
}

// UnimplementedDroneMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDroneMongoServiceServer struct{}

func (UnimplementedDroneMongoServiceServer) RegisterDrone(context.Context, *RegisterMongoDroneRequest) (*MongoDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDrone not implemented")
}
func (UnimplementedDroneMongoServiceServer) GetDrone(context.Context, *GetMongoDroneRequest) (*MongoDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrone not implemented")
}
func (UnimplementedDroneMongoServiceServer) UpdateDroneStatus(context.Context, *UpdateMongoDroneStatusRequest) (*MongoDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDroneStatus not implemented")
}
func (UnimplementedDroneMongoServiceServer) FindAvailableDrone(context.Context, *FindAvailableDroneRequest) (*MongoDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAvailableDrone not implemented")
}
func (UnimplementedDroneMongoServiceServer) ReserveDrone(context.Context, *ReserveMongoDroneRequest) (*MongoDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveDrone not implemented")
}
func (UnimplementedDroneMongoServiceServer) AssignDrone(context.Context, *AssignMongoDroneRequest) (*MongoDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDrone not implemented")
}
func (UnimplementedDroneMongoServiceServer) ListDrones(context.Context, *ListMongoDronesRequest) (*ListMongoDronesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrones not implemented")
}
func (UnimplementedDroneMongoServiceServer) mustEmbedUnimplementedDroneMongoServiceServer() {}
func (UnimplementedDroneMongoServiceServer) testEmbeddedByValue()                           {}

// UnsafeDroneMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneMongoServiceServer will
// result in compilation errors.
type UnsafeDroneMongoServiceServer interface {
	mustEmbedUnimplementedDroneMongoServiceServer()
}

func RegisterDroneMongoServiceServer(s grpc.ServiceRegistrar, srv DroneMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedDroneMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DroneMongoService_ServiceDesc, srv)
}

func _DroneMongoService_RegisterDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMongoDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).RegisterDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_RegisterDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).RegisterDrone(ctx, req.(*RegisterMongoDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneMongoService_GetDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).GetDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_GetDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).GetDrone(ctx, req.(*GetMongoDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneMongoService_UpdateDroneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMongoDroneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).UpdateDroneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_UpdateDroneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).UpdateDroneStatus(ctx, req.(*UpdateMongoDroneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneMongoService_FindAvailableDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAvailableDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).FindAvailableDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_FindAvailableDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).FindAvailableDrone(ctx, req.(*FindAvailableDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneMongoService_ReserveDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveMongoDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).ReserveDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_ReserveDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).ReserveDrone(ctx, req.(*ReserveMongoDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneMongoService_AssignDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignMongoDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).AssignDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_AssignDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).AssignDrone(ctx, req.(*AssignMongoDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneMongoService_ListDrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMongoDronesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneMongoServiceServer).ListDrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneMongoService_ListDrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneMongoServiceServer).ListDrones(ctx, req.(*ListMongoDronesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DroneMongoService_ServiceDesc is the grpc.ServiceDesc for DroneMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.DroneMongoService",
	HandlerType: (*DroneMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDrone",
			Handler:    _DroneMongoService_RegisterDrone_Handler,
		},
		{
			MethodName: "GetDrone",
			Handler:    _DroneMongoService_GetDrone_Handler,
		},
		{
			MethodName: "UpdateDroneStatus",
			Handler:    _DroneMongoService_UpdateDroneStatus_Handler,
		},
		{
			MethodName: "FindAvailableDrone",
			Handler:    _DroneMongoService_FindAvailableDrone_Handler,
		},
		{
			MethodName: "ReserveDrone",
			Handler:    _DroneMongoService_ReserveDrone_Handler,
		},
		{
			MethodName: "AssignDrone",
			Handler:    _DroneMongoService_AssignDrone_Handler,
		},
		{
			MethodName: "ListDrones",
			Handler:    _DroneMongoService_ListDrones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	FlightMongoService_AddNoFlyZone_FullMethodName  = "/mongodb_service.FlightMongoService/AddNoFlyZone"
	FlightMongoService_GetNoFlyZones_FullMethodName = "/mongodb_service.FlightMongoService/GetNoFlyZones"
)

// FlightMongoServiceClient is the client API for FlightMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightMongoServiceClient interface {
	AddNoFlyZone(ctx context.Context, in *AddMongoNoFlyZoneRequest, opts ...grpc.CallOption) (*MongoNoFlyZoneResponse, error)
	GetNoFlyZones(ctx context.Context, in *GetMongoNoFlyZonesRequest, opts ...grpc.CallOption) (*ListMongoNoFlyZonesResponse, error)
}

type flightMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightMongoServiceClient(cc grpc.ClientConnInterface) FlightMongoServiceClient {
	return &flightMongoServiceClient{cc}
}

func (c *flightMongoServiceClient) AddNoFlyZone(ctx context.Context, in *AddMongoNoFlyZoneRequest, opts ...grpc.CallOption) (*MongoNoFlyZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoNoFlyZoneResponse)
	err := c.cc.Invoke(ctx, FlightMongoService_AddNoFlyZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightMongoServiceClient) GetNoFlyZones(ctx context.Context, in *GetMongoNoFlyZonesRequest, opts ...grpc.CallOption) (*ListMongoNoFlyZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMongoNoFlyZonesResponse)
	err := c.cc.Invoke(ctx, FlightMongoService_GetNoFlyZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightMongoServiceServer is the server API for FlightMongoService service.
// All implementations must embed UnimplementedFlightMongoServiceServer
// for forward compatibility.
type FlightMongoServiceServer interface {
	AddNoFlyZone(context.Context, *AddMongoNoFlyZoneRequest) (*MongoNoFlyZoneResponse, error)
	GetNoFlyZones(context.Context, *GetMongoNoFlyZonesRequest) (*ListMongoNoFlyZonesResponse, error)
	mustEmbedUnimplementedFlightMongoServiceServer()
}

// UnimplementedFlightMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightMongoServiceServer struct{}

func (UnimplementedFlightMongoServiceServer) AddNoFlyZone(context.Context, *AddMongoNoFlyZoneRequest) (*MongoNoFlyZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNoFlyZone not implemented")
}
func (UnimplementedFlightMongoServiceServer) GetNoFlyZones(context.Context, *GetMongoNoFlyZonesRequest) (*ListMongoNoFlyZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoFlyZones not implemented")
}
func (UnimplementedFlightMongoServiceServer) mustEmbedUnimplementedFlightMongoServiceServer() {}
func (UnimplementedFlightMongoServiceServer) testEmbeddedByValue()                            {}

// UnsafeFlightMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightMongoServiceServer will
// result in compilation errors.
type UnsafeFlightMongoServiceServer interface {
	mustEmbedUnimplementedFlightMongoServiceServer()
}

func RegisterFlightMongoServiceServer(s grpc.ServiceRegistrar, srv FlightMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedFlightMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightMongoService_ServiceDesc, srv)
}

func _FlightMongoService_AddNoFlyZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMongoNoFlyZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightMongoServiceServer).AddNoFlyZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightMongoService_AddNoFlyZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightMongoServiceServer).AddNoFlyZone(ctx, req.(*AddMongoNoFlyZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightMongoService_GetNoFlyZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoNoFlyZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightMongoServiceServer).GetNoFlyZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightMongoService_GetNoFlyZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightMongoServiceServer).GetNoFlyZones(ctx, req.(*GetMongoNoFlyZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightMongoService_ServiceDesc is the grpc.ServiceDesc for FlightMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.FlightMongoService",
	HandlerType: (*FlightMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNoFlyZone",
			Handler:    _FlightMongoService_AddNoFlyZone_Handler,
		},
		{
			MethodName: "GetNoFlyZones",
			Handler:    _FlightMongoService_GetNoFlyZones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	OperationsMongoService_RegisterStation_FullMethodName = "/mongodb_service.OperationsMongoService/RegisterStation"
	OperationsMongoService_GetStations_FullMethodName     = "/mongodb_service.OperationsMongoService/GetStations"
	OperationsMongoService_SaveMaintenance_FullMethodName = "/mongodb_service.OperationsMongoService/SaveMaintenance"
)

// OperationsMongoServiceClient is the client API for OperationsMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationsMongoServiceClient interface {
	RegisterStation(ctx context.Context, in *RegisterMongoStationRequest, opts ...grpc.CallOption) (*MongoStationResponse, error)
	GetStations(ctx context.Context, in *GetMongoStationsRequest, opts ...grpc.CallOption) (*ListMongoStationsResponse, error)
	SaveMaintenance(ctx context.Context, in *SaveMongoMaintenanceRequest, opts ...grpc.CallOption) (*MongoMaintenanceResponse, error)
}

type operationsMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationsMongoServiceClient(cc grpc.ClientConnInterface) OperationsMongoServiceClient {
	return &operationsMongoServiceClient{cc}
}

func (c *operationsMongoServiceClient) RegisterStation(ctx context.Context, in *RegisterMongoStationRequest, opts ...grpc.CallOption) (*MongoStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoStationResponse)
	err := c.cc.Invoke(ctx, OperationsMongoService_RegisterStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsMongoServiceClient) GetStations(ctx context.Context, in *GetMongoStationsRequest, opts ...grpc.CallOption) (*ListMongoStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMongoStationsResponse)
	err := c.cc.Invoke(ctx, OperationsMongoService_GetStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsMongoServiceClient) SaveMaintenance(ctx context.Context, in *SaveMongoMaintenanceRequest, opts ...grpc.CallOption) (*MongoMaintenanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoMaintenanceResponse)
	err := c.cc.Invoke(ctx, OperationsMongoService_SaveMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsMongoServiceServer is the server API for OperationsMongoService service.
// All implementations must embed UnimplementedOperationsMongoServiceServer
// for forward compatibility.
type OperationsMongoServiceServer interface {
	RegisterStation(context.Context, *RegisterMongoStationRequest) (*MongoStationResponse, error)
	GetStations(context.Context, *GetMongoStationsRequest) (*ListMongoStationsResponse, error)
	SaveMaintenance(context.Context, *SaveMongoMaintenanceRequest) (*MongoMaintenanceResponse, error)
	mustEmbedUnimplementedOperationsMongoServiceServer()
}

// UnimplementedOperationsMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationsMongoServiceServer struct{}

func (UnimplementedOperationsMongoServiceServer) RegisterStation(context.Context, *RegisterMongoStationRequest) (*MongoStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterStation not implemented")
}
func (UnimplementedOperationsMongoServiceServer) GetStations(context.Context, *GetMongoStationsRequest) (*ListMongoStationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStations not implemented")
}
func (UnimplementedOperationsMongoServiceServer) SaveMaintenance(context.Context, *SaveMongoMaintenanceRequest) (*MongoMaintenanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveMaintenance not implemented")
}
func (UnimplementedOperationsMongoServiceServer) mustEmbedUnimplementedOperationsMongoServiceServer() {
}
func (UnimplementedOperationsMongoServiceServer) testEmbeddedByValue() {}

// UnsafeOperationsMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationsMongoServiceServer will
// result in compilation errors.
type UnsafeOperationsMongoServiceServer interface {
	mustEmbedUnimplementedOperationsMongoServiceServer()
}

func RegisterOperationsMongoServiceServer(s grpc.ServiceRegistrar, srv OperationsMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedOperationsMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationsMongoService_ServiceDesc, srv)
}

func _OperationsMongoService_RegisterStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMongoStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsMongoServiceServer).RegisterStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsMongoService_RegisterStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsMongoServiceServer).RegisterStation(ctx, req.(*RegisterMongoStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsMongoService_GetStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsMongoServiceServer).GetStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsMongoService_GetStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsMongoServiceServer).GetStations(ctx, req.(*GetMongoStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsMongoService_SaveMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMongoMaintenanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsMongoServiceServer).SaveMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsMongoService_SaveMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsMongoServiceServer).SaveMaintenance(ctx, req.(*SaveMongoMaintenanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationsMongoService_ServiceDesc is the grpc.ServiceDesc for OperationsMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationsMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.OperationsMongoService",
	HandlerType: (*OperationsMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterStation",
			Handler:    _OperationsMongoService_RegisterStation_Handler,
		},
		{
			MethodName: "GetStations",
			Handler:    _OperationsMongoService_GetStations_Handler,
		},
		{
			MethodName: "SaveMaintenance",
			Handler:    _OperationsMongoService_SaveMaintenance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	DeliveryMongoService_SaveDelivery_FullMethodName = "/mongodb_service.DeliveryMongoService/SaveDelivery"
	DeliveryMongoService_GetDelivery_FullMethodName  = "/mongodb_service.DeliveryMongoService/GetDelivery"
)

// DeliveryMongoServiceClient is the client API for DeliveryMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryMongoServiceClient interface {
	SaveDelivery(ctx context.Context, in *SaveMongoDeliveryRequest, opts ...grpc.CallOption) (*MongoDeliveryResponse, error)
	GetDelivery(ctx context.Context, in *GetMongoDeliveryRequest, opts ...grpc.CallOption) (*MongoDeliveryResponse, error)
}

type deliveryMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryMongoServiceClient(cc grpc.ClientConnInterface) DeliveryMongoServiceClient {
	return &deliveryMongoServiceClient{cc}
}

func (c *deliveryMongoServiceClient) SaveDelivery(ctx context.Context, in *SaveMongoDeliveryRequest, opts ...grpc.CallOption) (*MongoDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDeliveryResponse)
	err := c.cc.Invoke(ctx, DeliveryMongoService_SaveDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryMongoServiceClient) GetDelivery(ctx context.Context, in *GetMongoDeliveryRequest, opts ...grpc.CallOption) (*MongoDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDeliveryResponse)
	err := c.cc.Invoke(ctx, DeliveryMongoService_GetDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryMongoServiceServer is the server API for DeliveryMongoService service.
// All implementations must embed UnimplementedDeliveryMongoServiceServer
// for forward compatibility.
type DeliveryMongoServiceServer interface {
	SaveDelivery(context.Context, *SaveMongoDeliveryRequest) (*MongoDeliveryResponse, error)
	GetDelivery(context.Context, *GetMongoDeliveryRequest) (*MongoDeliveryResponse, error)
	mustEmbedUnimplementedDeliveryMongoServiceServer()
}

// UnimplementedDeliveryMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryMongoServiceServer struct{}

func (UnimplementedDeliveryMongoServiceServer) SaveDelivery(context.Context, *SaveMongoDeliveryRequest) (*MongoDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveDelivery not implemented")
}
func (UnimplementedDeliveryMongoServiceServer) GetDelivery(context.Context, *GetMongoDeliveryRequest) (*MongoDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelivery not implemented")
}
func (UnimplementedDeliveryMongoServiceServer) mustEmbedUnimplementedDeliveryMongoServiceServer() {}
func (UnimplementedDeliveryMongoServiceServer) testEmbeddedByValue()                              {}

// UnsafeDeliveryMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryMongoServiceServer will
// result in compilation errors.
type UnsafeDeliveryMongoServiceServer interface {
	mustEmbedUnimplementedDeliveryMongoServiceServer()
}

func RegisterDeliveryMongoServiceServer(s grpc.ServiceRegistrar, srv DeliveryMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryMongoService_ServiceDesc, srv)
}

func _DeliveryMongoService_SaveDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMongoDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryMongoServiceServer).SaveDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryMongoService_SaveDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryMongoServiceServer).SaveDelivery(ctx, req.(*SaveMongoDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryMongoService_GetDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryMongoServiceServer).GetDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryMongoService_GetDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryMongoServiceServer).GetDelivery(ctx, req.(*GetMongoDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryMongoService_ServiceDesc is the grpc.ServiceDesc for DeliveryMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.DeliveryMongoService",
	HandlerType: (*DeliveryMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveDelivery",
			Handler:    _DeliveryMongoService_SaveDelivery_Handler,
		},
		{
			MethodName: "GetDelivery",
			Handler:    _DeliveryMongoService_GetDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	PaymentMongoService_SaveTransaction_FullMethodName      = "/mongodb_service.PaymentMongoService/SaveTransaction"
	PaymentMongoService_GetUserWallet_FullMethodName        = "/mongodb_service.PaymentMongoService/GetUserWallet"
	PaymentMongoService_UpdateUserWallet_FullMethodName     = "/mongodb_service.PaymentMongoService/UpdateUserWallet"
	PaymentMongoService_ListUserTransactions_FullMethodName = "/mongodb_service.PaymentMongoService/ListUserTransactions"
)

// PaymentMongoServiceClient is the client API for PaymentMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentMongoServiceClient interface {
	SaveTransaction(ctx context.Context, in *SaveMongoTxRequest, opts ...grpc.CallOption) (*MongoTxResponse, error)
	GetUserWallet(ctx context.Context, in *GetUserWalletRequest, opts ...grpc.CallOption) (*MongoWalletResponse, error)
	UpdateUserWallet(ctx context.Context, in *UpdateUserWalletRequest, opts ...grpc.CallOption) (*MongoWalletResponse, error)
	ListUserTransactions(ctx context.Context, in *ListUserTxRequest, opts ...grpc.CallOption) (*ListUserTxResponse, error)
}

type paymentMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentMongoServiceClient(cc grpc.ClientConnInterface) PaymentMongoServiceClient {
	return &paymentMongoServiceClient{cc}
}

func (c *paymentMongoServiceClient) SaveTransaction(ctx context.Context, in *SaveMongoTxRequest, opts ...grpc.CallOption) (*MongoTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoTxResponse)
	err := c.cc.Invoke(ctx, PaymentMongoService_SaveTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentMongoServiceClient) GetUserWallet(ctx context.Context, in *GetUserWalletRequest, opts ...grpc.CallOption) (*MongoWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoWalletResponse)
	err := c.cc.Invoke(ctx, PaymentMongoService_GetUserWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentMongoServiceClient) UpdateUserWallet(ctx context.Context, in *UpdateUserWalletRequest, opts ...grpc.CallOption) (*MongoWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoWalletResponse)
	err := c.cc.Invoke(ctx, PaymentMongoService_UpdateUserWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentMongoServiceClient) ListUserTransactions(ctx context.Context, in *ListUserTxRequest, opts ...grpc.CallOption) (*ListUserTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserTxResponse)
	err := c.cc.Invoke(ctx, PaymentMongoService_ListUserTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentMongoServiceServer is the server API for PaymentMongoService service.
// All implementations must embed UnimplementedPaymentMongoServiceServer
// for forward compatibility.
type PaymentMongoServiceServer interface {
	SaveTransaction(context.Context, *SaveMongoTxRequest) (*MongoTxResponse, error)
	GetUserWallet(context.Context, *GetUserWalletRequest) (*MongoWalletResponse, error)
	UpdateUserWallet(context.Context, *UpdateUserWalletRequest) (*MongoWalletResponse, error)
	ListUserTransactions(context.Context, *ListUserTxRequest) (*ListUserTxResponse, error)
	mustEmbedUnimplementedPaymentMongoServiceServer()
}

// UnimplementedPaymentMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentMongoServiceServer struct{}

func (UnimplementedPaymentMongoServiceServer) SaveTransaction(context.Context, *SaveMongoTxRequest) (*MongoTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveTransaction not implemented")
}
func (UnimplementedPaymentMongoServiceServer) GetUserWallet(context.Context, *GetUserWalletRequest) (*MongoWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserWallet not implemented")
}
func (UnimplementedPaymentMongoServiceServer) UpdateUserWallet(context.Context, *UpdateUserWalletRequest) (*MongoWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserWallet not implemented")
}
func (UnimplementedPaymentMongoServiceServer) ListUserTransactions(context.Context, *ListUserTxRequest) (*ListUserTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserTransactions not implemented")
}
func (UnimplementedPaymentMongoServiceServer) mustEmbedUnimplementedPaymentMongoServiceServer() {}
func (UnimplementedPaymentMongoServiceServer) testEmbeddedByValue()                             {}

// UnsafePaymentMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentMongoServiceServer will
// result in compilation errors.
type UnsafePaymentMongoServiceServer interface {
	mustEmbedUnimplementedPaymentMongoServiceServer()
}

func RegisterPaymentMongoServiceServer(s grpc.ServiceRegistrar, srv PaymentMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentMongoService_ServiceDesc, srv)
}

func _PaymentMongoService_SaveTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMongoTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentMongoServiceServer).SaveTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentMongoService_SaveTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentMongoServiceServer).SaveTransaction(ctx, req.(*SaveMongoTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentMongoService_GetUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentMongoServiceServer).GetUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentMongoService_GetUserWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentMongoServiceServer).GetUserWallet(ctx, req.(*GetUserWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentMongoService_UpdateUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentMongoServiceServer).UpdateUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentMongoService_UpdateUserWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentMongoServiceServer).UpdateUserWallet(ctx, req.(*UpdateUserWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentMongoService_ListUserTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentMongoServiceServer).ListUserTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentMongoService_ListUserTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentMongoServiceServer).ListUserTransactions(ctx, req.(*ListUserTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentMongoService_ServiceDesc is the grpc.ServiceDesc for PaymentMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.PaymentMongoService",
	HandlerType: (*PaymentMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTransaction",
			Handler:    _PaymentMongoService_SaveTransaction_Handler,
		},
		{
			MethodName: "GetUserWallet",
			Handler:    _PaymentMongoService_GetUserWallet_Handler,
		},
		{
			MethodName: "UpdateUserWallet",
			Handler:    _PaymentMongoService_UpdateUserWallet_Handler,
		},
		{
			MethodName: "ListUserTransactions",
			Handler:    _PaymentMongoService_ListUserTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	WarehouseMongoService_SaveBusiness_FullMethodName  = "/mongodb_service.WarehouseMongoService/SaveBusiness"
	WarehouseMongoService_SaveWarehouse_FullMethodName = "/mongodb_service.WarehouseMongoService/SaveWarehouse"
	WarehouseMongoService_SaveInventory_FullMethodName = "/mongodb_service.WarehouseMongoService/SaveInventory"
	WarehouseMongoService_GetInventory_FullMethodName  = "/mongodb_service.WarehouseMongoService/GetInventory"
)

// WarehouseMongoServiceClient is the client API for WarehouseMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseMongoServiceClient interface {
	SaveBusiness(ctx context.Context, in *SaveMongoBusinessRequest, opts ...grpc.CallOption) (*MongoBusinessResponse, error)
	SaveWarehouse(ctx context.Context, in *SaveMongoWarehouseRequest, opts ...grpc.CallOption) (*MongoWarehouseResponse, error)
	SaveInventory(ctx context.Context, in *SaveMongoInventoryRequest, opts ...grpc.CallOption) (*MongoInventoryResponse, error)
	GetInventory(ctx context.Context, in *GetMongoInventoryRequest, opts ...grpc.CallOption) (*ListMongoInventoryResponse, error)
}

type warehouseMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseMongoServiceClient(cc grpc.ClientConnInterface) WarehouseMongoServiceClient {
	return &warehouseMongoServiceClient{cc}
}

func (c *warehouseMongoServiceClient) SaveBusiness(ctx context.Context, in *SaveMongoBusinessRequest, opts ...grpc.CallOption) (*MongoBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoBusinessResponse)
	err := c.cc.Invoke(ctx, WarehouseMongoService_SaveBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseMongoServiceClient) SaveWarehouse(ctx context.Context, in *SaveMongoWarehouseRequest, opts ...grpc.CallOption) (*MongoWarehouseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoWarehouseResponse)
	err := c.cc.Invoke(ctx, WarehouseMongoService_SaveWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseMongoServiceClient) SaveInventory(ctx context.Context, in *SaveMongoInventoryRequest, opts ...grpc.CallOption) (*MongoInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoInventoryResponse)
	err := c.cc.Invoke(ctx, WarehouseMongoService_SaveInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseMongoServiceClient) GetInventory(ctx context.Context, in *GetMongoInventoryRequest, opts ...grpc.CallOption) (*ListMongoInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMongoInventoryResponse)
	err := c.cc.Invoke(ctx, WarehouseMongoService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseMongoServiceServer is the server API for WarehouseMongoService service.
// All implementations must embed UnimplementedWarehouseMongoServiceServer
// for forward compatibility.
type WarehouseMongoServiceServer interface {
	SaveBusiness(context.Context, *SaveMongoBusinessRequest) (*MongoBusinessResponse, error)
	SaveWarehouse(context.Context, *SaveMongoWarehouseRequest) (*MongoWarehouseResponse, error)
	SaveInventory(context.Context, *SaveMongoInventoryRequest) (*MongoInventoryResponse, error)
	GetInventory(context.Context, *GetMongoInventoryRequest) (*ListMongoInventoryResponse, error)
	mustEmbedUnimplementedWarehouseMongoServiceServer()
}

// UnimplementedWarehouseMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarehouseMongoServiceServer struct{}

func (UnimplementedWarehouseMongoServiceServer) SaveBusiness(context.Context, *SaveMongoBusinessRequest) (*MongoBusinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveBusiness not implemented")
}
func (UnimplementedWarehouseMongoServiceServer) SaveWarehouse(context.Context, *SaveMongoWarehouseRequest) (*MongoWarehouseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveWarehouse not implemented")
}
func (UnimplementedWarehouseMongoServiceServer) SaveInventory(context.Context, *SaveMongoInventoryRequest) (*MongoInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveInventory not implemented")
}
func (UnimplementedWarehouseMongoServiceServer) GetInventory(context.Context, *GetMongoInventoryRequest) (*ListMongoInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedWarehouseMongoServiceServer) mustEmbedUnimplementedWarehouseMongoServiceServer() {}
func (UnimplementedWarehouseMongoServiceServer) testEmbeddedByValue()                               {}

// UnsafeWarehouseMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseMongoServiceServer will
// result in compilation errors.
type UnsafeWarehouseMongoServiceServer interface {
	mustEmbedUnimplementedWarehouseMongoServiceServer()
}

func RegisterWarehouseMongoServiceServer(s grpc.ServiceRegistrar, srv WarehouseMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedWarehouseMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarehouseMongoService_ServiceDesc, srv)
}

func _WarehouseMongoService_SaveBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMongoBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseMongoServiceServer).SaveBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseMongoService_SaveBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseMongoServiceServer).SaveBusiness(ctx, req.(*SaveMongoBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseMongoService_SaveWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMongoWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseMongoServiceServer).SaveWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseMongoService_SaveWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseMongoServiceServer).SaveWarehouse(ctx, req.(*SaveMongoWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseMongoService_SaveInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMongoInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseMongoServiceServer).SaveInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseMongoService_SaveInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseMongoServiceServer).SaveInventory(ctx, req.(*SaveMongoInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseMongoService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseMongoServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseMongoService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseMongoServiceServer).GetInventory(ctx, req.(*GetMongoInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseMongoService_ServiceDesc is the grpc.ServiceDesc for WarehouseMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.WarehouseMongoService",
	HandlerType: (*WarehouseMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveBusiness",
			Handler:    _WarehouseMongoService_SaveBusiness_Handler,
		},
		{
			MethodName: "SaveWarehouse",
			Handler:    _WarehouseMongoService_SaveWarehouse_Handler,
		},
		{
			MethodName: "SaveInventory",
			Handler:    _WarehouseMongoService_SaveInventory_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _WarehouseMongoService_GetInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}

const (
	AnalyticsMongoService_SaveAnalyticsSnapshot_FullMethodName      = "/mongodb_service.AnalyticsMongoService/SaveAnalyticsSnapshot"
	AnalyticsMongoService_GetLatestAnalyticsSnapshot_FullMethodName = "/mongodb_service.AnalyticsMongoService/GetLatestAnalyticsSnapshot"
	AnalyticsMongoService_SaveFailureEvent_FullMethodName           = "/mongodb_service.AnalyticsMongoService/SaveFailureEvent"
	AnalyticsMongoService_ListFailureEvents_FullMethodName          = "/mongodb_service.AnalyticsMongoService/ListFailureEvents"
)

// AnalyticsMongoServiceClient is the client API for AnalyticsMongoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsMongoServiceClient interface {
	SaveAnalyticsSnapshot(ctx context.Context, in *SaveAnalyticsSnapshotRequest, opts ...grpc.CallOption) (*MongoAnalyticsResponse, error)
	GetLatestAnalyticsSnapshot(ctx context.Context, in *GetAnalyticsSnapshotRequest, opts ...grpc.CallOption) (*MongoAnalyticsSnapshotData, error)
	SaveFailureEvent(ctx context.Context, in *SaveFailureEventRequest, opts ...grpc.CallOption) (*MongoAnalyticsResponse, error)
	ListFailureEvents(ctx context.Context, in *ListFailureEventsRequest, opts ...grpc.CallOption) (*ListFailureEventsResponse, error)
}

type analyticsMongoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsMongoServiceClient(cc grpc.ClientConnInterface) AnalyticsMongoServiceClient {
	return &analyticsMongoServiceClient{cc}
}

func (c *analyticsMongoServiceClient) SaveAnalyticsSnapshot(ctx context.Context, in *SaveAnalyticsSnapshotRequest, opts ...grpc.CallOption) (*MongoAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsMongoService_SaveAnalyticsSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsMongoServiceClient) GetLatestAnalyticsSnapshot(ctx context.Context, in *GetAnalyticsSnapshotRequest, opts ...grpc.CallOption) (*MongoAnalyticsSnapshotData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoAnalyticsSnapshotData)
	err := c.cc.Invoke(ctx, AnalyticsMongoService_GetLatestAnalyticsSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsMongoServiceClient) SaveFailureEvent(ctx context.Context, in *SaveFailureEventRequest, opts ...grpc.CallOption) (*MongoAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsMongoService_SaveFailureEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsMongoServiceClient) ListFailureEvents(ctx context.Context, in *ListFailureEventsRequest, opts ...grpc.CallOption) (*ListFailureEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFailureEventsResponse)
	err := c.cc.Invoke(ctx, AnalyticsMongoService_ListFailureEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsMongoServiceServer is the server API for AnalyticsMongoService service.
// All implementations must embed UnimplementedAnalyticsMongoServiceServer
// for forward compatibility.
type AnalyticsMongoServiceServer interface {
	SaveAnalyticsSnapshot(context.Context, *SaveAnalyticsSnapshotRequest) (*MongoAnalyticsResponse, error)
	GetLatestAnalyticsSnapshot(context.Context, *GetAnalyticsSnapshotRequest) (*MongoAnalyticsSnapshotData, error)
	SaveFailureEvent(context.Context, *SaveFailureEventRequest) (*MongoAnalyticsResponse, error)
	ListFailureEvents(context.Context, *ListFailureEventsRequest) (*ListFailureEventsResponse, error)
	mustEmbedUnimplementedAnalyticsMongoServiceServer()
}

// UnimplementedAnalyticsMongoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsMongoServiceServer struct{}

func (UnimplementedAnalyticsMongoServiceServer) SaveAnalyticsSnapshot(context.Context, *SaveAnalyticsSnapshotRequest) (*MongoAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAnalyticsSnapshot not implemented")
}
func (UnimplementedAnalyticsMongoServiceServer) GetLatestAnalyticsSnapshot(context.Context, *GetAnalyticsSnapshotRequest) (*MongoAnalyticsSnapshotData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestAnalyticsSnapshot not implemented")
}
func (UnimplementedAnalyticsMongoServiceServer) SaveFailureEvent(context.Context, *SaveFailureEventRequest) (*MongoAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveFailureEvent not implemented")
}
func (UnimplementedAnalyticsMongoServiceServer) ListFailureEvents(context.Context, *ListFailureEventsRequest) (*ListFailureEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFailureEvents not implemented")
}
func (UnimplementedAnalyticsMongoServiceServer) mustEmbedUnimplementedAnalyticsMongoServiceServer() {}
func (UnimplementedAnalyticsMongoServiceServer) testEmbeddedByValue()                               {}

// UnsafeAnalyticsMongoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsMongoServiceServer will
// result in compilation errors.
type UnsafeAnalyticsMongoServiceServer interface {
	mustEmbedUnimplementedAnalyticsMongoServiceServer()
}

func RegisterAnalyticsMongoServiceServer(s grpc.ServiceRegistrar, srv AnalyticsMongoServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsMongoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsMongoService_ServiceDesc, srv)
}

func _AnalyticsMongoService_SaveAnalyticsSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAnalyticsSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsMongoServiceServer).SaveAnalyticsSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsMongoService_SaveAnalyticsSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsMongoServiceServer).SaveAnalyticsSnapshot(ctx, req.(*SaveAnalyticsSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsMongoService_GetLatestAnalyticsSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyticsSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsMongoServiceServer).GetLatestAnalyticsSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsMongoService_GetLatestAnalyticsSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsMongoServiceServer).GetLatestAnalyticsSnapshot(ctx, req.(*GetAnalyticsSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsMongoService_SaveFailureEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFailureEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsMongoServiceServer).SaveFailureEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsMongoService_SaveFailureEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsMongoServiceServer).SaveFailureEvent(ctx, req.(*SaveFailureEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsMongoService_ListFailureEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFailureEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsMongoServiceServer).ListFailureEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsMongoService_ListFailureEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsMongoServiceServer).ListFailureEvents(ctx, req.(*ListFailureEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsMongoService_ServiceDesc is the grpc.ServiceDesc for AnalyticsMongoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsMongoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb_service.AnalyticsMongoService",
	HandlerType: (*AnalyticsMongoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveAnalyticsSnapshot",
			Handler:    _AnalyticsMongoService_SaveAnalyticsSnapshot_Handler,
		},
		{
			MethodName: "GetLatestAnalyticsSnapshot",
			Handler:    _AnalyticsMongoService_GetLatestAnalyticsSnapshot_Handler,
		},
		{
			MethodName: "SaveFailureEvent",
			Handler:    _AnalyticsMongoService_SaveFailureEvent_Handler,
		},
		{
			MethodName: "ListFailureEvents",
			Handler:    _AnalyticsMongoService_ListFailureEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo_service/mongodb_service.proto",
}
