// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/monitoring_service/monitoring_service.proto

package monitoring_service_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequestMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	StatusCode      int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	DurationMs      int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Timestamp       string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IpAddress       string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent       string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestMetadata map[string]string      `protobuf:"bytes,9,rep,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PayloadSize     int64                  `protobuf:"varint,10,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogRequestMessage) Reset() {
	*x = LogRequestMessage{}
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequestMessage) ProtoMessage() {}

func (x *LogRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequestMessage.ProtoReflect.Descriptor instead.
func (*LogRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_service_monitoring_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequestMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRequestMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequestMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogRequestMessage) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogRequestMessage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *LogRequestMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogRequestMessage) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LogRequestMessage) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LogRequestMessage) GetRequestMetadata() map[string]string {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

func (x *LogRequestMessage) GetPayloadSize() int64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

type SystemMetricsMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp        string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,5,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes    int64                  `protobuf:"varint,6,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   int64                  `protobuf:"varint,7,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	SystemMetadata   map[string]string      `protobuf:"bytes,8,rep,name=system_metadata,json=systemMetadata,proto3" json:"system_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemMetricsMessage) Reset() {
	*x = SystemMetricsMessage{}
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsMessage) ProtoMessage() {}

func (x *SystemMetricsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsMessage.ProtoReflect.Descriptor instead.
func (*SystemMetricsMessage) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_service_monitoring_service_proto_rawDescGZIP(), []int{1}
}

func (x *SystemMetricsMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SystemMetricsMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SystemMetricsMessage) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemMetricsMessage) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemMetricsMessage) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemMetricsMessage) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *SystemMetricsMessage) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *SystemMetricsMessage) GetSystemMetadata() map[string]string {
	if x != nil {
		return x.SystemMetadata
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_service_monitoring_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // Optional specific date to rotate/upload (e.g. YYYY-MM-DD), if empty defaults to today
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTriggerRequest) Reset() {
	*x = UploadTriggerRequest{}
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTriggerRequest) ProtoMessage() {}

func (x *UploadTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTriggerRequest.ProtoReflect.Descriptor instead.
func (*UploadTriggerRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_service_monitoring_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadTriggerRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type UploadTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTriggerResponse) Reset() {
	*x = UploadTriggerResponse{}
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTriggerResponse) ProtoMessage() {}

func (x *UploadTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_service_monitoring_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTriggerResponse.ProtoReflect.Descriptor instead.
func (*UploadTriggerResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_service_monitoring_service_proto_rawDescGZIP(), []int{4}
}

func (x *UploadTriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadTriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_monitoring_service_monitoring_service_proto protoreflect.FileDescriptor

const file_proto_monitoring_service_monitoring_service_proto_rawDesc = "" +
	"\n" +
	"1proto/monitoring_service/monitoring_service.proto\x12\x12monitoring_service\"\xce\x03\n" +
	"\x11LogRequestMessage\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x12e\n" +
	"\x10request_metadata\x18\t \x03(\v2:.monitoring_service.LogRequestMessage.RequestMetadataEntryR\x0frequestMetadata\x12!\n" +
	"\fpayload_size\x18\n" +
	" \x01(\x03R\vpayloadSize\x1aB\n" +
	"\x14RequestMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x03\n" +
	"\x14SystemMetricsMessage\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x05 \x01(\x03R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x06 \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\a \x01(\x03R\x0ediskTotalBytes\x12e\n" +
	"\x0fsystem_metadata\x18\b \x03(\v2<.monitoring_service.SystemMetricsMessage.SystemMetadataEntryR\x0esystemMetadata\x1aA\n" +
	"\x13SystemMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x14UploadTriggerRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"K\n" +
	"\x15UploadTriggerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb3\x02\n" +
	"\x11MonitoringService\x12T\n" +
	"\n" +
	"LogRequest\x12%.monitoring_service.LogRequestMessage\x1a\x1f.monitoring_service.LogResponse\x12]\n" +
	"\x10LogSystemMetrics\x12(.monitoring_service.SystemMetricsMessage\x1a\x1f.monitoring_service.LogResponse\x12i\n" +
	"\x12TriggerDailyUpload\x12(.monitoring_service.UploadTriggerRequest\x1a).monitoring_service.UploadTriggerResponseBZZXgithub.com/RevenueIQ/revenueiq_dev_kit/proto/monitoring_service;monitoring_service_protob\x06proto3"

var (
	file_proto_monitoring_service_monitoring_service_proto_rawDescOnce sync.Once
	file_proto_monitoring_service_monitoring_service_proto_rawDescData []byte
)

func file_proto_monitoring_service_monitoring_service_proto_rawDescGZIP() []byte {
	file_proto_monitoring_service_monitoring_service_proto_rawDescOnce.Do(func() {
		file_proto_monitoring_service_monitoring_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitoring_service_monitoring_service_proto_rawDesc), len(file_proto_monitoring_service_monitoring_service_proto_rawDesc)))
	})
	return file_proto_monitoring_service_monitoring_service_proto_rawDescData
}

var file_proto_monitoring_service_monitoring_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_monitoring_service_monitoring_service_proto_goTypes = []any{
	(*LogRequestMessage)(nil),     // 0: monitoring_service.LogRequestMessage
	(*SystemMetricsMessage)(nil),  // 1: monitoring_service.SystemMetricsMessage
	(*LogResponse)(nil),           // 2: monitoring_service.LogResponse
	(*UploadTriggerRequest)(nil),  // 3: monitoring_service.UploadTriggerRequest
	(*UploadTriggerResponse)(nil), // 4: monitoring_service.UploadTriggerResponse
	nil,                           // 5: monitoring_service.LogRequestMessage.RequestMetadataEntry
	nil,                           // 6: monitoring_service.SystemMetricsMessage.SystemMetadataEntry
}
var file_proto_monitoring_service_monitoring_service_proto_depIdxs = []int32{
	5, // 0: monitoring_service.LogRequestMessage.request_metadata:type_name -> monitoring_service.LogRequestMessage.RequestMetadataEntry
	6, // 1: monitoring_service.SystemMetricsMessage.system_metadata:type_name -> monitoring_service.SystemMetricsMessage.SystemMetadataEntry
	0, // 2: monitoring_service.MonitoringService.LogRequest:input_type -> monitoring_service.LogRequestMessage
	1, // 3: monitoring_service.MonitoringService.LogSystemMetrics:input_type -> monitoring_service.SystemMetricsMessage
	3, // 4: monitoring_service.MonitoringService.TriggerDailyUpload:input_type -> monitoring_service.UploadTriggerRequest
	2, // 5: monitoring_service.MonitoringService.LogRequest:output_type -> monitoring_service.LogResponse
	2, // 6: monitoring_service.MonitoringService.LogSystemMetrics:output_type -> monitoring_service.LogResponse
	4, // 7: monitoring_service.MonitoringService.TriggerDailyUpload:output_type -> monitoring_service.UploadTriggerResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_monitoring_service_monitoring_service_proto_init() }
func file_proto_monitoring_service_monitoring_service_proto_init() {
	if File_proto_monitoring_service_monitoring_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitoring_service_monitoring_service_proto_rawDesc), len(file_proto_monitoring_service_monitoring_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitoring_service_monitoring_service_proto_goTypes,
		DependencyIndexes: file_proto_monitoring_service_monitoring_service_proto_depIdxs,
		MessageInfos:      file_proto_monitoring_service_monitoring_service_proto_msgTypes,
	}.Build()
	File_proto_monitoring_service_monitoring_service_proto = out.File
	file_proto_monitoring_service_monitoring_service_proto_goTypes = nil
	file_proto_monitoring_service_monitoring_service_proto_depIdxs = nil
}
