// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/operations_service/operations_service.proto

package operations_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationsService_RegisterChargingStation_FullMethodName = "/operations_service.OperationsService/RegisterChargingStation"
	OperationsService_GetChargingStations_FullMethodName     = "/operations_service.OperationsService/GetChargingStations"
	OperationsService_QueueDroneForCharging_FullMethodName   = "/operations_service.OperationsService/QueueDroneForCharging"
	OperationsService_ScheduleMaintenance_FullMethodName     = "/operations_service.OperationsService/ScheduleMaintenance"
	OperationsService_CompleteRepair_FullMethodName          = "/operations_service.OperationsService/CompleteRepair"
)

// OperationsServiceClient is the client API for OperationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationsServiceClient interface {
	RegisterChargingStation(ctx context.Context, in *RegisterStationRequest, opts ...grpc.CallOption) (*StationResponse, error)
	GetChargingStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error)
	QueueDroneForCharging(ctx context.Context, in *QueueChargingRequest, opts ...grpc.CallOption) (*QueueChargingResponse, error)
	ScheduleMaintenance(ctx context.Context, in *ScheduleMaintenanceRequest, opts ...grpc.CallOption) (*MaintenanceResponse, error)
	CompleteRepair(ctx context.Context, in *CompleteRepairRequest, opts ...grpc.CallOption) (*RepairResponse, error)
}

type operationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationsServiceClient(cc grpc.ClientConnInterface) OperationsServiceClient {
	return &operationsServiceClient{cc}
}

func (c *operationsServiceClient) RegisterChargingStation(ctx context.Context, in *RegisterStationRequest, opts ...grpc.CallOption) (*StationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StationResponse)
	err := c.cc.Invoke(ctx, OperationsService_RegisterChargingStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) GetChargingStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStationsResponse)
	err := c.cc.Invoke(ctx, OperationsService_GetChargingStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) QueueDroneForCharging(ctx context.Context, in *QueueChargingRequest, opts ...grpc.CallOption) (*QueueChargingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueChargingResponse)
	err := c.cc.Invoke(ctx, OperationsService_QueueDroneForCharging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ScheduleMaintenance(ctx context.Context, in *ScheduleMaintenanceRequest, opts ...grpc.CallOption) (*MaintenanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceResponse)
	err := c.cc.Invoke(ctx, OperationsService_ScheduleMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) CompleteRepair(ctx context.Context, in *CompleteRepairRequest, opts ...grpc.CallOption) (*RepairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepairResponse)
	err := c.cc.Invoke(ctx, OperationsService_CompleteRepair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsServiceServer is the server API for OperationsService service.
// All implementations must embed UnimplementedOperationsServiceServer
// for forward compatibility.
type OperationsServiceServer interface {
	RegisterChargingStation(context.Context, *RegisterStationRequest) (*StationResponse, error)
	GetChargingStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error)
	QueueDroneForCharging(context.Context, *QueueChargingRequest) (*QueueChargingResponse, error)
	ScheduleMaintenance(context.Context, *ScheduleMaintenanceRequest) (*MaintenanceResponse, error)
	CompleteRepair(context.Context, *CompleteRepairRequest) (*RepairResponse, error)
	mustEmbedUnimplementedOperationsServiceServer()
}

// UnimplementedOperationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationsServiceServer struct{}

func (UnimplementedOperationsServiceServer) RegisterChargingStation(context.Context, *RegisterStationRequest) (*StationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterChargingStation not implemented")
}
func (UnimplementedOperationsServiceServer) GetChargingStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChargingStations not implemented")
}
func (UnimplementedOperationsServiceServer) QueueDroneForCharging(context.Context, *QueueChargingRequest) (*QueueChargingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueueDroneForCharging not implemented")
}
func (UnimplementedOperationsServiceServer) ScheduleMaintenance(context.Context, *ScheduleMaintenanceRequest) (*MaintenanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleMaintenance not implemented")
}
func (UnimplementedOperationsServiceServer) CompleteRepair(context.Context, *CompleteRepairRequest) (*RepairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteRepair not implemented")
}
func (UnimplementedOperationsServiceServer) mustEmbedUnimplementedOperationsServiceServer() {}
func (UnimplementedOperationsServiceServer) testEmbeddedByValue()                           {}

// UnsafeOperationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationsServiceServer will
// result in compilation errors.
type UnsafeOperationsServiceServer interface {
	mustEmbedUnimplementedOperationsServiceServer()
}

func RegisterOperationsServiceServer(s grpc.ServiceRegistrar, srv OperationsServiceServer) {
	// If the following call panics, it indicates UnimplementedOperationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationsService_ServiceDesc, srv)
}

func _OperationsService_RegisterChargingStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).RegisterChargingStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_RegisterChargingStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).RegisterChargingStation(ctx, req.(*RegisterStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_GetChargingStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).GetChargingStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_GetChargingStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).GetChargingStations(ctx, req.(*GetStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_QueueDroneForCharging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueChargingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).QueueDroneForCharging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_QueueDroneForCharging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).QueueDroneForCharging(ctx, req.(*QueueChargingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ScheduleMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleMaintenanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ScheduleMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ScheduleMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ScheduleMaintenance(ctx, req.(*ScheduleMaintenanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_CompleteRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).CompleteRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_CompleteRepair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).CompleteRepair(ctx, req.(*CompleteRepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationsService_ServiceDesc is the grpc.ServiceDesc for OperationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations_service.OperationsService",
	HandlerType: (*OperationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChargingStation",
			Handler:    _OperationsService_RegisterChargingStation_Handler,
		},
		{
			MethodName: "GetChargingStations",
			Handler:    _OperationsService_GetChargingStations_Handler,
		},
		{
			MethodName: "QueueDroneForCharging",
			Handler:    _OperationsService_QueueDroneForCharging_Handler,
		},
		{
			MethodName: "ScheduleMaintenance",
			Handler:    _OperationsService_ScheduleMaintenance_Handler,
		},
		{
			MethodName: "CompleteRepair",
			Handler:    _OperationsService_CompleteRepair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/operations_service/operations_service.proto",
}
