// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/fleet_service/fleet_service.proto

package fleet_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_RegisterDrone_FullMethodName     = "/fleet_service.FleetService/RegisterDrone"
	FleetService_GetDrone_FullMethodName          = "/fleet_service.FleetService/GetDrone"
	FleetService_UpdateDroneStatus_FullMethodName = "/fleet_service.FleetService/UpdateDroneStatus"
	FleetService_ReserveDrone_FullMethodName      = "/fleet_service.FleetService/ReserveDrone"
	FleetService_AssignDrone_FullMethodName       = "/fleet_service.FleetService/AssignDrone"
	FleetService_ListDrones_FullMethodName        = "/fleet_service.FleetService/ListDrones"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetServiceClient interface {
	RegisterDrone(ctx context.Context, in *RegisterDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error)
	GetDrone(ctx context.Context, in *GetDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error)
	UpdateDroneStatus(ctx context.Context, in *UpdateDroneStatusRequest, opts ...grpc.CallOption) (*DroneResponse, error)
	ReserveDrone(ctx context.Context, in *ReserveDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error)
	AssignDrone(ctx context.Context, in *AssignDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error)
	ListDrones(ctx context.Context, in *ListDronesRequest, opts ...grpc.CallOption) (*ListDronesResponse, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) RegisterDrone(ctx context.Context, in *RegisterDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, FleetService_RegisterDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetDrone(ctx context.Context, in *GetDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, FleetService_GetDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) UpdateDroneStatus(ctx context.Context, in *UpdateDroneStatusRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, FleetService_UpdateDroneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ReserveDrone(ctx context.Context, in *ReserveDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, FleetService_ReserveDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) AssignDrone(ctx context.Context, in *AssignDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, FleetService_AssignDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListDrones(ctx context.Context, in *ListDronesRequest, opts ...grpc.CallOption) (*ListDronesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDronesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListDrones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
type FleetServiceServer interface {
	RegisterDrone(context.Context, *RegisterDroneRequest) (*DroneResponse, error)
	GetDrone(context.Context, *GetDroneRequest) (*DroneResponse, error)
	UpdateDroneStatus(context.Context, *UpdateDroneStatusRequest) (*DroneResponse, error)
	ReserveDrone(context.Context, *ReserveDroneRequest) (*DroneResponse, error)
	AssignDrone(context.Context, *AssignDroneRequest) (*DroneResponse, error)
	ListDrones(context.Context, *ListDronesRequest) (*ListDronesResponse, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) RegisterDrone(context.Context, *RegisterDroneRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDrone not implemented")
}
func (UnimplementedFleetServiceServer) GetDrone(context.Context, *GetDroneRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrone not implemented")
}
func (UnimplementedFleetServiceServer) UpdateDroneStatus(context.Context, *UpdateDroneStatusRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDroneStatus not implemented")
}
func (UnimplementedFleetServiceServer) ReserveDrone(context.Context, *ReserveDroneRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveDrone not implemented")
}
func (UnimplementedFleetServiceServer) AssignDrone(context.Context, *AssignDroneRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDrone not implemented")
}
func (UnimplementedFleetServiceServer) ListDrones(context.Context, *ListDronesRequest) (*ListDronesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrones not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call panics, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_RegisterDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RegisterDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RegisterDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RegisterDrone(ctx, req.(*RegisterDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetDrone(ctx, req.(*GetDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_UpdateDroneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDroneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).UpdateDroneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_UpdateDroneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).UpdateDroneStatus(ctx, req.(*UpdateDroneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ReserveDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ReserveDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ReserveDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ReserveDrone(ctx, req.(*ReserveDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_AssignDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).AssignDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_AssignDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).AssignDrone(ctx, req.(*AssignDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListDrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDronesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListDrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListDrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListDrones(ctx, req.(*ListDronesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet_service.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDrone",
			Handler:    _FleetService_RegisterDrone_Handler,
		},
		{
			MethodName: "GetDrone",
			Handler:    _FleetService_GetDrone_Handler,
		},
		{
			MethodName: "UpdateDroneStatus",
			Handler:    _FleetService_UpdateDroneStatus_Handler,
		},
		{
			MethodName: "ReserveDrone",
			Handler:    _FleetService_ReserveDrone_Handler,
		},
		{
			MethodName: "AssignDrone",
			Handler:    _FleetService_AssignDrone_Handler,
		},
		{
			MethodName: "ListDrones",
			Handler:    _FleetService_ListDrones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fleet_service/fleet_service.proto",
}
