// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/audit/audit.proto

package audit_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_LogAction_FullMethodName          = "/revenueiq.audit.AuditService/LogAction"
	AuditService_GetAuditTrail_FullMethodName      = "/revenueiq.audit.AuditService/GetAuditTrail"
	AuditService_GetActionsByEntity_FullMethodName = "/revenueiq.audit.AuditService/GetActionsByEntity"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	LogAction(ctx context.Context, in *LogActionRequest, opts ...grpc.CallOption) (*LogActionResponse, error)
	GetAuditTrail(ctx context.Context, in *GetAuditTrailRequest, opts ...grpc.CallOption) (*GetAuditTrailResponse, error)
	GetActionsByEntity(ctx context.Context, in *GetEntityActionsRequest, opts ...grpc.CallOption) (*GetAuditTrailResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) LogAction(ctx context.Context, in *LogActionRequest, opts ...grpc.CallOption) (*LogActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogActionResponse)
	err := c.cc.Invoke(ctx, AuditService_LogAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetAuditTrail(ctx context.Context, in *GetAuditTrailRequest, opts ...grpc.CallOption) (*GetAuditTrailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditTrailResponse)
	err := c.cc.Invoke(ctx, AuditService_GetAuditTrail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetActionsByEntity(ctx context.Context, in *GetEntityActionsRequest, opts ...grpc.CallOption) (*GetAuditTrailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditTrailResponse)
	err := c.cc.Invoke(ctx, AuditService_GetActionsByEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	LogAction(context.Context, *LogActionRequest) (*LogActionResponse, error)
	GetAuditTrail(context.Context, *GetAuditTrailRequest) (*GetAuditTrailResponse, error)
	GetActionsByEntity(context.Context, *GetEntityActionsRequest) (*GetAuditTrailResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) LogAction(context.Context, *LogActionRequest) (*LogActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogAction not implemented")
}
func (UnimplementedAuditServiceServer) GetAuditTrail(context.Context, *GetAuditTrailRequest) (*GetAuditTrailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditTrail not implemented")
}
func (UnimplementedAuditServiceServer) GetActionsByEntity(context.Context, *GetEntityActionsRequest) (*GetAuditTrailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActionsByEntity not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_LogAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).LogAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_LogAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).LogAction(ctx, req.(*LogActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetAuditTrail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditTrailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetAuditTrail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetAuditTrail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetAuditTrail(ctx, req.(*GetAuditTrailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetActionsByEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetActionsByEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetActionsByEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetActionsByEntity(ctx, req.(*GetEntityActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revenueiq.audit.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogAction",
			Handler:    _AuditService_LogAction_Handler,
		},
		{
			MethodName: "GetAuditTrail",
			Handler:    _AuditService_GetAuditTrail_Handler,
		},
		{
			MethodName: "GetActionsByEntity",
			Handler:    _AuditService_GetActionsByEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/audit/audit.proto",
}
